In [1]:
import pandas as pd
import os

In [2]:
# To run with Debug:
#DIRNAME = os.path.dirname(__file__)
#ASSETS_FOLDER = os.path.join(DIRNAME, 'assets')
##ASSETS_FOLDER_OBJ = "data_analysis\\assets"
#ASSETS_FOLDER_ITENS = os.listdir(ASSETS_FOLDER)# ("data_analysis/assets")


# To run with terminal:
ASSETS_FOLDER = "assets"
ASSETS_FOLDER_ITENS = os.listdir(ASSETS_FOLDER)# ("assets")

INITIAL_TAG_DIGITS = '7103'

In [3]:
# Replace spaces in filenames with underlines
def replace_space_with_underline(file_name):
    return file_name.replace(" ", "_")

In [4]:
# Convert excel files into csv
def converting_excel_file_into_csv_file(folder_obj, file):        
    # read excel   
    df_xlsx = pd.read_excel(os.path.join(folder_obj, file))
    # change file format
    file_in_csv = file.replace(".xlsx", ".csv")
    # transform excel to csv file with path to store the CSV file
    df_xlsx.to_csv(os.path.join(folder_obj, file_in_csv), index=False)

In [5]:
# Check if some excel file has not been converted into csv yet
def check_for_excel_files():
    all_my_files = []
    n = 0
    for file in ASSETS_FOLDER_ITENS:
        # put all the file names in the same format
        file = replace_space_with_underline(file).lower()
        all_my_files.append(file)
    
    # Create a copy of list
    for file in all_my_files[:]:
        if file.endswith('.xlsx'):
            print('- Excel file= ' + file)
            file_name = file.split('.', 1)[0] # remove everything (the format) after the dot
            # remove the excel file from my all_my_files list
            all_my_files.remove(file)            
            # check if another file with the same name in the folder exists
            if any(file_name in word for word in all_my_files):            
                print(f"-- Excellent! We've already converted the excel file \'{file_name}\' into csv file")
            else:
                print(f'-- Oh No! The excel file \'{file_name}\' has been not converted. Converting it into csv file...')
                # Call function "Convert excel files into csv"
                converting_excel_file_into_csv_file(ASSETS_FOLDER_OBJ, file)
                file_in_csv = file.replace(".xlsx", ".csv") 
                all_my_files.append(file_in_csv)
                print('---> ' + file_in_csv + ' has been created!')
                
    # Updated all_my_files List
    print('LAST: CSV files in the assets folder: ', all_my_files)

In [6]:
class TurtleData:
    """Commom base class for all turtle's data """

    # CELL_REPORT_SUPPLIER = 'A1'
    # CELL_REPORT_FORMAT = 'B2'
    # CELL_HEADERS_ROW = 'B3'
    # CELL_DATA_SOURCE = 'B4'
    # CELL_TDC_VERSION = 'B5'

    # CELL_CTN_TAG = 'B7'
    # CELL_COMMENT = 'B8'
    # CELL_IRIDIUM_IMEI = 'B9'

    # REPORT_PERIOD_BEGINS = 'B11'
    # REPORT_PERIOD_ENDS = 'B12'
    
    C1 = 'Acquisition Time'
    C2 ='Acquisition Start Time'
    C3 ='Iridium CEP Radius'
    C4 ='Iridium Latitude'
    C5 ='Iridium Longitude'
    C6 ='GPS Fix Time'
    C7 ='GPS Fix Attempt'
    C8 ='GPS Latitude'
    C9 ='GPS Longitude'
    C10 ='GPS UTM Zone'
    C11 ='GPS UTM Northing'
    C12 ='GPS UTM Easting'
    C13 ='GPS Altitude'
    C14 ='GPS Horizontal Error'
    C15 ='GPS Horizontal Dilution'
    C16 ='GPS Satellite Bitmap'
    C17 ='GPS Satellite Count'
    C18 ='Underwater Percentage'
    C19 ='Dive Count'
    C20 ='Average Dive Duration'
    C21 ='Dive Duration Standard Deviation'
    C22 ='Maximum Dive Duration'
    C23 ='Maximum Dive Depth'
    C24 ='Duration Limit 1 Dive Count'
    C25 ='Duration Limit 2 Dive Count'
    C26 ='Duration Limit 3 Dive Count'
    C27 ='Duration Limit 4 Dive Count'
    C28 ='Duration Limit 5 Dive Count'
    C29 ='Duration Limit 6 Dive Count'
    C30 ='Layer 1 Percentage'
    C31 ='Layer 2 Percentage'
    C32 ='Layer 3 Percentage'
    C33 ='Layer 4 Percentage'
    C34 ='Layer 5 Percentage'
    C35 ='Layer 6 Percentage'
    C36 ='Layer 7 Percentage'
    C37 ='Layer 8 Percentage'
    C38 ='Layer 9 Percentage'
    C39 ='Layer 10 Percentage'
    C40 ='Layer 1 Dive Count'
    C41 ='Layer 2 Dive Count'
    C42 ='Layer 3 Dive Count'
    C43 ='Layer 4 Dive Count'
    C44 ='Layer 5 Dive Count'
    C45 ='Layer 6 Dive Count'
    C46 ='Layer 7 Dive Count'
    C47 ='Layer 8 Dive Count'
    C48 ='Layer 9 Dive Count'
    C49 ='Layer 10 Dive Count'
    C50 ='Temperature'
    C51 ='Satellite Uplink'
    C52 ='Receive Time'
    C53 ='Repetition Count'
    C54 ='Low Voltage'
    C55 ='Mortality'
    C56 ='Saltwater Failsafe'
    C57 ='Iridium Command'
    C58 ='Schedule Set'
    C59 ='Diagnostic Dive Data'
    C60 ='Predeployment Data'
    C61 ='Error'
    col_names = list([
        C1, C2, C3, C4, C5, C6, C7, C8, C9, C10, 
        C11, C12, C13, C14, C15, C16, C17, C18, C19, C20, 
        C21, C22, C23, C24, C25, C26, C27, C28, C29, C30, 
        C31, C32, C33, C34, C35, C36, C37, C38, C39, C40, 
        C41, C42, C43, C44, C45, C46, C47, C48, C49, C50, 
        C51, C52, C53, C54, C55, C56, C57, C58, C59, C60, 
        C61
    ])
    
    def __init__(self, tag):
        #self.supplier = 'A1' #temporaryDf['A1']
        #self.__dict__= {}
        self.turtleTag = tag
        self.df = pd.DataFrame()
        #self.header_row = []
        #self.specific_turtle_dfs_list = []
        #self.df = self.df.reindex(columns = list(self.header_row)) 
        #self.df.columns = list(self.header_row)

        #self.df = pd.DataFrame({'Empty' : []})
        #df = df.reindex(columns = header_list) 
        #mydf = mydf.reindex(mydf.columns.tolist() + ['newcol1','newcol2'], axis=1)  # version > 0.20.0
    
    #def __repr__(self):
        #return self.turtleTag
    def addElement(self, row, header):
        self.__dict__= dict(zip(header, row))

    def addDataFromCsv(self, filename):
        #print(os.path.abspath(os.getcwd()))
        #def readFile(self, fileName):
        #temporaryDf = pd.read_csv(filename, names=TurtleData.col_names) # error_bad_lines=False)# , index_col=False, sep='delimiter', header=None)
        temporaryDf = pd.read_csv(filename, skiprows=23, names=TurtleData.col_names)
        #temporaryDf = pd.read_csv(file, index_col=False)
        
        # Remove/Change Header
        #header_row = temporaryDf.iloc[21] # Take Row 21 # Finding the Data Header
        
        # Cancel the Index Column Name to None
        #header_row.name = ''
        
        # Filter/Remove the Satellite Informations in the First Lines
        #temporaryDf = temporaryDf[22:]
        
        # Drop the Satellite Informations, to access only the data
        #temporaryDf.drop(temporaryDf.index[0:21])
        # Set the new Header
        #temporaryDf.columns = list(header_row)
        
        # Reset Index
        #temporaryDf.reset_index(drop=True, inplace=True)

        #self.df.reset_index(drop=True, inplace=True)
        #self.specific_turtle_dfs_list.append(temporaryDf)

        #self.df = temporaryDf.reindex(columns = header_row)
        #self.header_row = header_row
        #self.df = self.df.reindex(columns = list(self.header_row)) 
        #self.df.columns = self.header_row
        
        print(f' CURRENT DF IS {self.df}') 
        print(f' TEMPORARY DF IS {temporaryDf}')
        
        
        self.df = self.df.append(temporaryDf, ignore_index=True)
        self.df.sort_values("Acquisition Time", inplace = True)
        #frame = pd.concat(li, axis=0, ignore_index=True)
        #for df in self.specific_turtle_dfs_list:
        #self.df.concat((df for df in specific_turtle_dfs_list), axis=0, ignore_index=True)
        
        #print(f' The self.df of {filename} is now: {self.df}') 


        # start = temporaryDf (CELL_HEADER_START)
        # temporaryDf.removeTUTToprima(start)
        # self.df.aggiungi temporaryDf
        #return print(df)

    def getTag(self):
        return self.turtleTag

    def getDf(self):
        self.df.set_option("display.max_rows", None, "display.max_columns", None)
        return self.df

In [7]:
def getTurtlesData():
    split_char = '_'
    csvs = []        
    turtlesData = []
    turtleDfs = []
    for file in ASSETS_FOLDER_ITENS:
        #print(os.getcwd())
        #print(DIRNAME)
        #print(ASSETS_FOLDER)
        # filename = file
        if file.endswith('.csv'):
            # csvs.append(file)
            # currentFileCsv = ASSETS_FOLDER + '\\' + file
            # put all the file names in the same format
            csv_string_filename = replace_space_with_underline(file).lower()
            filename_splitted = csv_string_filename.split(split_char)                        
            for word in filename_splitted:
                #print(word)
                if word.startswith(INITIAL_TAG_DIGITS):
                    csvs.append(file)
                    currentFileCsv = ASSETS_FOLDER + '\\' + file                 
                    #print(file)
                    print("Found TAG ("+ word +") in filename , check if tag is already associated with an object...")

                    #--------------------

                    foundTurtleData = None
                    # check inside the list if the turtle has already been created with that tag (word)
                    for obj in turtlesData:
                        if obj.getTag() == word:
                            foundTurtleData = obj
                            break    
                    #--------------------    

                    if foundTurtleData == None:
                        print("Instance for TAG ("+ word +") NOT found! Creating a new instance.")
                        # create a TurtleData obj with the turtle tag
                        foundTurtleData = TurtleData(word)
                        turtlesData.append(foundTurtleData)
                    else:
                        print("Instance for TAG ("+ word +") already exist, skipping object creation!")

                    # for the instances turtleData objs in the list (for each turtle tag):
                    #foundTurtleData.addDataFromCsv(file)
                    #print(ASSETS_FOLDER_OBJ)
                    # print(currentFileCsv)                    
                    # csvData = pd.read_csv(currentFileCsv)
                    # #turtleDfs.append(csvData)
                    # print(csvData)
                    #print("Files in %r: %s" % (ASSETS_FOLDER, ASSETS_FOLDER_ITENS))
                    #if file in ASSETS_FOLDER_ITENS:
                        #print('yes!')
                        #print(ASSETS_FOLDER + '\\' + file)
                        #DATA = pd.read_csv(currentFileCsv)
                    foundTurtleData.addDataFromCsv(currentFileCsv)

            #csv_turtle_files.append(csv)
    #for filename in csvs:
        #print(filename)
        #if filename in ASSETS_FOLDER_ITENS:
            #print('yes!')

    #for turtleData in turtlesData:
        ###print(os.path.abspath(os.getcwd()))
        #print(turtleData.getTag())
        #print(turtleData.getDf)
        ###print(f'DataFrame is {turtleData.addDataFromCsv(ASSETS_FOLDER_OBJ, file)}')
    return turtlesData

In [8]:
check_for_excel_files()

- Excel file= mytest.xlsx
-- Excellent! We've already converted the excel file 'mytest' into csv file
- Excel file= tag_710333a_20_sept.xlsx
-- Excellent! We've already converted the excel file 'tag_710333a_20_sept' into csv file
LAST: CSV files in the assets folder:  ['710333a_93_condensed.csv', '710348a_49_condensed.csv', 'mytest.csv', 'tag_710333a_20_sept.csv']

In [9]:
turtlesData = getTurtlesData()

Found TAG (710333a) in filename , check if tag is already associated with an object...
Instance for TAG (710333a) NOT found! Creating a new instance.
 CURRENT DF IS Empty DataFrame
Columns: []
Index: []
 TEMPORARY DF IS          Acquisition Time Acquisition Start Time  Iridium CEP Radius  \
0     2019.07.15 14:15:00    2019.07.15 14:15:00                 NaN
1     2019.07.15 14:15:08    2019.07.15 14:15:00                 NaN
2     2019.07.15 14:30:00    2019.07.15 14:15:00                 NaN
3     2019.07.15 14:30:00    2019.07.15 14:30:00                 NaN
4     2019.07.15 14:30:10    2019.07.15 14:30:00                 NaN
...                   ...                    ...                 ...
6903  2021.02.11 05:55:38    2021.02.11 05:00:00                 NaN
6904  2021.02.11 06:00:00    2021.02.11 04:00:00                 NaN
6905  2021.02.11 06:00:10    2021.02.11 06:00:00                 NaN
6906  2021.02.11 08:00:00    2021.02.11 06:00:00                 NaN
6907  2021.02.11 10:57:07    2021.02.11 10:57:07                 3.0

      Iridium Latitude  Iridium Longitude         GPS Fix Time  \
0                  NaN                NaN                  NaN
1                  NaN                NaN  2019.07.15 14:15:08
2                  NaN                NaN                  NaN
3                  NaN                NaN                  NaN
4                  NaN                NaN  2019.07.15 14:30:10
...                ...                ...                  ...
6903               NaN                NaN  2021.02.11 05:55:38
6904               NaN                NaN                  NaN
6905               NaN                NaN  2021.02.11 06:00:10
6906               NaN                NaN                  NaN
6907          38.72645            11.8152                  NaN

     GPS Fix Attempt  GPS Latitude  GPS Longitude GPS UTM Zone  ...  \
0                NaN           NaN            NaN          NaN  ...
1       Resolved QFP     33.384364    -111.811310          12S  ...
2                NaN           NaN            NaN          NaN  ...
3                NaN           NaN            NaN          NaN  ...
4       Resolved QFP     33.384385    -111.811292          12S  ...
...              ...           ...            ...          ...  ...
6903    Resolved QFP     38.720644      11.825379          32S  ...
6904             NaN           NaN            NaN          NaN  ...
6905    Resolved QFP     38.720648      11.825217          32S  ...
6906             NaN           NaN            NaN          NaN  ...
6907             NaN           NaN            NaN          NaN  ...

             Receive Time  Repetition Count  Low Voltage  Mortality  \
0     2019.07.15 14:40:24                 1          NaN        NaN
1     2019.07.15 14:40:24                 1          NaN        NaN
2     2019.07.15 14:40:24                 1          NaN        NaN
3     2019.07.15 14:40:24                 1          NaN        NaN
4     2019.07.15 14:40:24                 1          NaN        NaN
...                   ...               ...          ...        ...
6903  2021.02.11 10:57:07                 1          NaN        NaN
6904  2021.02.11 10:57:07                 1          NaN        NaN
6905  2021.02.11 10:57:07                 1          NaN        NaN
6906  2021.02.11 10:57:07                 1          NaN        NaN
6907  2021.02.11 10:57:07                 1           No        NaN

      Saltwater Failsafe Iridium Command  Schedule Set  \
0                    NaN             NaN     Roof Test
1                    NaN             NaN     Roof Test
2                    NaN             NaN     Roof Test
3                    NaN             NaN     Roof Test
4                    NaN             NaN     Roof Test
...                  ...             ...           ...
6903                 NaN             NaN       Primary
6904                 NaN             NaN       Primary
6905                 NaN             NaN       Primary
6906                 NaN             NaN       Primary
6907                  No             NaN           NaN

           Diagnostic Dive Data  Predeployment Data  Error
0                           NaN                  No    NaN
1                           NaN                  No    NaN
2                           NaN                  No    NaN
3                           NaN                  No    NaN
4                           NaN                  No    NaN
...                         ...                 ...    ...
6903                        NaN                  No    NaN
6904                        NaN                  No    NaN
6905                        NaN                  No    NaN
6906                        NaN                  No    NaN
6907  23094 7698 8878 3 0 0 2 1                  No    NaN

[6908 rows x 61 columns]
Found TAG (710348a) in filename , check if tag is already associated with an object...
Instance for TAG (710348a) NOT found! Creating a new instance.
 CURRENT DF IS Empty DataFrame
Columns: []
Index: []
 TEMPORARY DF IS          Acquisition Time Acquisition Start Time  Iridium CEP Radius  \
0     2019.07.15 14:15:00    2019.07.15 14:15:00                 NaN
1     2019.07.15 14:15:08    2019.07.15 14:15:00                 NaN
2     2019.07.15 14:30:00    2019.07.15 14:15:00                 NaN
3     2019.07.15 14:30:00    2019.07.15 14:30:00                 NaN
4     2019.07.15 14:30:06    2019.07.15 14:30:00                 NaN
...                   ...                    ...                 ...
5666  2021.02.11 04:00:00    2021.02.11 02:00:00                 NaN
5667  2021.02.11 05:50:10    2021.02.11 05:00:00                 NaN
5668  2021.02.11 06:00:00    2021.02.11 04:00:00                 NaN
5669  2021.02.11 06:41:28    2021.02.11 06:00:00                 NaN
5670  2021.02.11 10:40:30    2021.02.11 10:40:30                 4.0

      Iridium Latitude  Iridium Longitude         GPS Fix Time  \
0                  NaN                NaN                  NaN
1                  NaN                NaN  2019.07.15 14:15:08
2                  NaN                NaN                  NaN
3                  NaN                NaN                  NaN
4                  NaN                NaN  2019.07.15 14:30:06
...                ...                ...                  ...
5666               NaN                NaN                  NaN
5667               NaN                NaN  2021.02.11 05:50:10
5668               NaN                NaN                  NaN
5669               NaN                NaN  2021.02.11 06:41:28
5670          37.71965           17.37297                  NaN

     GPS Fix Attempt  GPS Latitude  GPS Longitude GPS UTM Zone  ...  \
0                NaN           NaN            NaN          NaN  ...
1       Resolved QFP     33.384380    -111.811327          12S  ...
2                NaN           NaN            NaN          NaN  ...
3                NaN           NaN            NaN          NaN  ...
4       Resolved QFP     33.384410    -111.811311          12S  ...
...              ...           ...            ...          ...  ...
5666             NaN           NaN            NaN          NaN  ...
5667    Resolved QFP     37.752154      17.380009          33S  ...
5668             NaN           NaN            NaN          NaN  ...
5669    Resolved QFP     37.742126      17.386460          33S  ...
5670             NaN           NaN            NaN          NaN  ...

             Receive Time  Repetition Count  Low Voltage  Mortality  \
0     2019.07.15 14:38:49                 1          NaN        NaN
1     2019.07.15 14:38:49                 1          NaN        NaN
2     2019.07.15 14:38:49                 1          NaN        NaN
3     2019.07.15 14:38:49                 1          NaN        NaN
4     2019.07.15 14:38:49                 1          NaN        NaN
...                   ...               ...          ...        ...
5666  2021.02.11 10:40:30                 1          NaN        NaN
5667  2021.02.11 10:40:30                 1          NaN        NaN
5668  2021.02.11 10:40:30                 1          NaN        NaN
5669  2021.02.11 10:40:30                 1          NaN        NaN
5670  2021.02.11 10:40:30                 1           No        NaN

      Saltwater Failsafe Iridium Command  Schedule Set Diagnostic Dive Data  \
0                    NaN             NaN     Roof Test                  NaN
1                    NaN             NaN     Roof Test                  NaN
2                    NaN             NaN     Roof Test                  NaN
3                    NaN             NaN     Roof Test                  NaN
4                    NaN             NaN     Roof Test                  NaN
...                  ...             ...           ...                  ...
5666                 NaN             NaN       Primary                  NaN
5667                 NaN             NaN       Primary                  NaN
5668                 NaN             NaN       Primary                  NaN
5669                 NaN             NaN       Primary                  NaN
5670                  No             NaN           NaN  0 0 13927 5 0 0 0 0

      Predeployment Data  Error
0                     No    NaN
1                     No    NaN
2                     No    NaN
3                     No    NaN
4                     No    NaN
...                  ...    ...
5666                  No    NaN
5667                  No    NaN
5668                  No    NaN
5669                  No    NaN
5670                  No    NaN

[5671 rows x 61 columns]
Found TAG (710333a) in filename , check if tag is already associated with an object...
Instance for TAG (710333a) already exist, skipping object creation!

 CURRENT DF IS          Acquisition Time Acquisition Start Time  Iridium CEP Radius  \
0     2019.07.15 14:15:00    2019.07.15 14:15:00                 NaN
1     2019.07.15 14:15:08    2019.07.15 14:15:00                 NaN
2     2019.07.15 14:30:00    2019.07.15 14:15:00                 NaN
3     2019.07.15 14:30:00    2019.07.15 14:30:00                 NaN
4     2019.07.15 14:30:10    2019.07.15 14:30:00                 NaN
...                   ...                    ...                 ...
6903  2021.02.11 05:55:38    2021.02.11 05:00:00                 NaN
6904  2021.02.11 06:00:00    2021.02.11 04:00:00                 NaN
6905  2021.02.11 06:00:10    2021.02.11 06:00:00                 NaN
6906  2021.02.11 08:00:00    2021.02.11 06:00:00                 NaN
6907  2021.02.11 10:57:07    2021.02.11 10:57:07                 3.0

      Iridium Latitude  Iridium Longitude         GPS Fix Time  \
0                  NaN                NaN                  NaN
1                  NaN                NaN  2019.07.15 14:15:08
2                  NaN                NaN                  NaN
3                  NaN                NaN                  NaN
4                  NaN                NaN  2019.07.15 14:30:10
...                ...                ...                  ...
6903               NaN                NaN  2021.02.11 05:55:38
6904               NaN                NaN                  NaN
6905               NaN                NaN  2021.02.11 06:00:10
6906               NaN                NaN                  NaN
6907          38.72645            11.8152                  NaN

     GPS Fix Attempt  GPS Latitude  GPS Longitude GPS UTM Zone  ...  \
0                NaN           NaN            NaN          NaN  ...
1       Resolved QFP     33.384364    -111.811310          12S  ...
2                NaN           NaN            NaN          NaN  ...
3                NaN           NaN            NaN          NaN  ...
4       Resolved QFP     33.384385    -111.811292          12S  ...
...              ...           ...            ...          ...  ...
6903    Resolved QFP     38.720644      11.825379          32S  ...
6904             NaN           NaN            NaN          NaN  ...
6905    Resolved QFP     38.720648      11.825217          32S  ...
6906             NaN           NaN            NaN          NaN  ...
6907             NaN           NaN            NaN          NaN  ...

             Receive Time  Repetition Count  Low Voltage  Mortality  \
0     2019.07.15 14:40:24                 1          NaN        NaN
1     2019.07.15 14:40:24                 1          NaN        NaN
2     2019.07.15 14:40:24                 1          NaN        NaN
3     2019.07.15 14:40:24                 1          NaN        NaN
4     2019.07.15 14:40:24                 1          NaN        NaN
...                   ...               ...          ...        ...
6903  2021.02.11 10:57:07                 1          NaN        NaN
6904  2021.02.11 10:57:07                 1          NaN        NaN
6905  2021.02.11 10:57:07                 1          NaN        NaN
6906  2021.02.11 10:57:07                 1          NaN        NaN
6907  2021.02.11 10:57:07                 1           No        NaN

      Saltwater Failsafe Iridium Command  Schedule Set  \
0                    NaN             NaN     Roof Test
1                    NaN             NaN     Roof Test
2                    NaN             NaN     Roof Test
3                    NaN             NaN     Roof Test
4                    NaN             NaN     Roof Test
...                  ...             ...           ...
6903                 NaN             NaN       Primary
6904                 NaN             NaN       Primary
6905                 NaN             NaN       Primary
6906                 NaN             NaN       Primary
6907                  No             NaN           NaN

           Diagnostic Dive Data  Predeployment Data  Error
0                           NaN                  No    NaN
1                           NaN                  No    NaN
2                           NaN                  No    NaN
3                           NaN                  No    NaN
4                           NaN                  No    NaN
...                         ...                 ...    ...
6903                        NaN                  No    NaN
6904                        NaN                  No    NaN
6905                        NaN                  No    NaN
6906                        NaN                  No    NaN
6907  23094 7698 8878 3 0 0 2 1                  No    NaN

[6908 rows x 61 columns]
 TEMPORARY DF IS          Acquisition Time Acquisition Start Time  Iridium CEP Radius  \
0     2020.07.09 23:00:09    2020.07.09 23:00:00                 NaN
1     2020.07.09 23:30:12    2020.07.09 23:30:00                 NaN
2     2020.07.10 00:00:00    2020.07.10 00:00:00                 NaN
3     2020.07.10 00:30:08    2020.07.10 00:30:00                 NaN
4     2020.07.10 01:00:08    2020.07.10 01:00:00                 NaN
...                   ...                    ...                 ...
2615  2020.09.21 03:01:42    2020.09.21 03:00:00                 NaN
2616  2020.09.21 04:00:00    2020.09.21 02:00:00                 NaN
2617  2020.09.21 04:00:18    2020.09.21 04:00:00                 NaN
2618  2020.09.21 05:00:05    2020.09.21 05:00:00                 NaN
2619  2020.09.21 06:00:14    2020.09.21 06:00:14                 7.0

      Iridium Latitude  Iridium Longitude         GPS Fix Time  \
0                  NaN                NaN  2020.07.09 23:00:09
1                  NaN                NaN  2020.07.09 23:30:12
2                  NaN                NaN                  NaN
3                  NaN                NaN  2020.07.10 00:30:08
4                  NaN                NaN  2020.07.10 01:00:08
...                ...                ...                  ...
2615               NaN                NaN  2020.09.21 03:01:42
2616               NaN                NaN                  NaN
2617               NaN                NaN  2020.09.21 04:00:18
2618               NaN                NaN  2020.09.21 05:00:05
2619          38.00282            4.28687                  NaN

               GPS Fix Attempt  GPS Latitude  GPS Longitude GPS UTM Zone  ...  \
0     Resolved QFP (Uncertain)     37.930044      16.068138          33S  ...
1                 Resolved QFP     37.930187      16.068178          33S  ...
2                          NaN           NaN            NaN          NaN  ...
3                 Resolved QFP     37.931116      16.069576          33S  ...
4                 Resolved QFP     37.931058      16.069576          33S  ...
...                        ...           ...            ...          ...  ...
2615            Unresolved QFP     38.038288       4.358534          31S  ...
2616                       NaN           NaN            NaN          NaN  ...
2617              Resolved QFP     38.031704       4.359388          31S  ...
2618              Resolved QFP     38.025555       4.359394          31S  ...
2619                       NaN           NaN            NaN          NaN  ...

             Receive Time  Repetition Count  Low Voltage  Mortality  \
0     2020.07.10 05:34:12                 1          NaN        NaN
1     2020.07.10 05:34:12                 1          NaN        NaN
2     2020.07.10 05:34:12                 1          NaN        NaN
3     2020.07.10 05:34:12                 1          NaN        NaN
4     2020.07.10 05:34:12                 1          NaN        NaN
...                   ...               ...          ...        ...
2615  2020.09.21 06:00:14                 1          NaN        NaN
2616  2020.09.21 06:00:14                 1          NaN        NaN
2617  2020.09.21 06:00:14                 1          NaN        NaN
2618  2020.09.21 06:00:14                 1          NaN        NaN
2619  2020.09.21 06:00:14                 1           No        NaN

      Saltwater Failsafe Iridium Command  Schedule Set  Diagnostic Dive Data  \
0                    NaN             NaN       Primary                   NaN
1                    NaN             NaN       Primary                   NaN
2                    NaN             NaN       Primary                   NaN
3                    NaN             NaN       Primary                   NaN
4                    NaN             NaN       Primary                   NaN
...                  ...             ...           ...                   ...
2615                 NaN             NaN       Primary                   NaN
2616                 NaN             NaN       Primary                   NaN
2617                 NaN             NaN       Primary                   NaN
2618                 NaN             NaN       Primary                   NaN
2619                  No             NaN           NaN   0 0 1319 12 2 0 0 0

      Predeployment Data  Error
0                     No    NaN
1                     No    NaN
2                     No    NaN
3                     No    NaN
4                     No    NaN
...                  ...    ...
2615                  No    NaN
2616                  No    NaN
2617                  No    NaN
2618                  No    NaN
2619                  No    NaN

[2620 rows x 61 columns]

In [10]:
for turtleData in turtlesData:
        #print(os.path.abspath(os.getcwd()))
        print(turtleData.getTag())
        print(turtleData.df)
        #print(turtleData.getDf)

710333a
         Acquisition Time Acquisition Start Time  Iridium CEP Radius  \
0     2019.07.15 14:15:00    2019.07.15 14:15:00                 NaN
1     2019.07.15 14:15:08    2019.07.15 14:15:00                 NaN
2     2019.07.15 14:30:00    2019.07.15 14:15:00                 NaN
3     2019.07.15 14:30:00    2019.07.15 14:30:00                 NaN
4     2019.07.15 14:30:10    2019.07.15 14:30:00                 NaN
...                   ...                    ...                 ...
6903  2021.02.11 05:55:38    2021.02.11 05:00:00                 NaN
6904  2021.02.11 06:00:00    2021.02.11 04:00:00                 NaN
6905  2021.02.11 06:00:10    2021.02.11 06:00:00                 NaN
6906  2021.02.11 08:00:00    2021.02.11 06:00:00                 NaN
6907  2021.02.11 10:57:07    2021.02.11 10:57:07                 3.0

      Iridium Latitude  Iridium Longitude         GPS Fix Time  \
0                  NaN                NaN                  NaN
1                  NaN                NaN  2019.07.15 14:15:08
2                  NaN                NaN                  NaN
3                  NaN                NaN                  NaN
4                  NaN                NaN  2019.07.15 14:30:10
...                ...                ...                  ...
6903               NaN                NaN  2021.02.11 05:55:38
6904               NaN                NaN                  NaN
6905               NaN                NaN  2021.02.11 06:00:10
6906               NaN                NaN                  NaN
6907          38.72645            11.8152                  NaN

     GPS Fix Attempt  GPS Latitude  GPS Longitude GPS UTM Zone  ...  \
0                NaN           NaN            NaN          NaN  ...
1       Resolved QFP     33.384364    -111.811310          12S  ...
2                NaN           NaN            NaN          NaN  ...
3                NaN           NaN            NaN          NaN  ...
4       Resolved QFP     33.384385    -111.811292          12S  ...
...              ...           ...            ...          ...  ...
6903    Resolved QFP     38.720644      11.825379          32S  ...
6904             NaN           NaN            NaN          NaN  ...
6905    Resolved QFP     38.720648      11.825217          32S  ...
6906             NaN           NaN            NaN          NaN  ...
6907             NaN           NaN            NaN          NaN  ...

             Receive Time  Repetition Count  Low Voltage  Mortality  \
0     2019.07.15 14:40:24                 1          NaN        NaN
1     2019.07.15 14:40:24                 1          NaN        NaN
2     2019.07.15 14:40:24                 1          NaN        NaN
3     2019.07.15 14:40:24                 1          NaN        NaN
4     2019.07.15 14:40:24                 1          NaN        NaN
...                   ...               ...          ...        ...
6903  2021.02.11 10:57:07                 1          NaN        NaN
6904  2021.02.11 10:57:07                 1          NaN        NaN
6905  2021.02.11 10:57:07                 1          NaN        NaN
6906  2021.02.11 10:57:07                 1          NaN        NaN
6907  2021.02.11 10:57:07                 1           No        NaN

      Saltwater Failsafe Iridium Command  Schedule Set  \
0                    NaN             NaN     Roof Test
1                    NaN             NaN     Roof Test
2                    NaN             NaN     Roof Test
3                    NaN             NaN     Roof Test
4                    NaN             NaN     Roof Test
...                  ...             ...           ...
6903                 NaN             NaN       Primary
6904                 NaN             NaN       Primary
6905                 NaN             NaN       Primary
6906                 NaN             NaN       Primary
6907                  No             NaN           NaN

           Diagnostic Dive Data  Predeployment Data  Error
0                           NaN                  No    NaN
1                           NaN                  No    NaN
2                           NaN                  No    NaN
3                           NaN                  No    NaN
4                           NaN                  No    NaN
...                         ...                 ...    ...
6903                        NaN                  No    NaN
6904                        NaN                  No    NaN
6905                        NaN                  No    NaN
6906                        NaN                  No    NaN
6907  23094 7698 8878 3 0 0 2 1                  No    NaN

[9528 rows x 61 columns]
710348a
         Acquisition Time Acquisition Start Time  Iridium CEP Radius  \
0     2019.07.15 14:15:00    2019.07.15 14:15:00                 NaN
1     2019.07.15 14:15:08    2019.07.15 14:15:00                 NaN
2     2019.07.15 14:30:00    2019.07.15 14:15:00                 NaN
3     2019.07.15 14:30:00    2019.07.15 14:30:00                 NaN
4     2019.07.15 14:30:06    2019.07.15 14:30:00                 NaN
...                   ...                    ...                 ...
5666  2021.02.11 04:00:00    2021.02.11 02:00:00                 NaN
5667  2021.02.11 05:50:10    2021.02.11 05:00:00                 NaN
5668  2021.02.11 06:00:00    2021.02.11 04:00:00                 NaN
5669  2021.02.11 06:41:28    2021.02.11 06:00:00                 NaN
5670  2021.02.11 10:40:30    2021.02.11 10:40:30                 4.0

      Iridium Latitude  Iridium Longitude         GPS Fix Time  \
0                  NaN                NaN                  NaN
1                  NaN                NaN  2019.07.15 14:15:08
2                  NaN                NaN                  NaN
3                  NaN                NaN                  NaN
4                  NaN                NaN  2019.07.15 14:30:06
...                ...                ...                  ...
5666               NaN                NaN                  NaN
5667               NaN                NaN  2021.02.11 05:50:10
5668               NaN                NaN                  NaN
5669               NaN                NaN  2021.02.11 06:41:28
5670          37.71965           17.37297                  NaN

     GPS Fix Attempt  GPS Latitude  GPS Longitude GPS UTM Zone  ...  \
0                NaN           NaN            NaN          NaN  ...
1       Resolved QFP     33.384380    -111.811327          12S  ...
2                NaN           NaN            NaN          NaN  ...
3                NaN           NaN            NaN          NaN  ...
4       Resolved QFP     33.384410    -111.811311          12S  ...
...              ...           ...            ...          ...  ...
5666             NaN           NaN            NaN          NaN  ...
5667    Resolved QFP     37.752154      17.380009          33S  ...
5668             NaN           NaN            NaN          NaN  ...
5669    Resolved QFP     37.742126      17.386460          33S  ...
5670             NaN           NaN            NaN          NaN  ...

             Receive Time  Repetition Count  Low Voltage  Mortality  \
0     2019.07.15 14:38:49                 1          NaN        NaN
1     2019.07.15 14:38:49                 1          NaN        NaN
2     2019.07.15 14:38:49                 1          NaN        NaN
3     2019.07.15 14:38:49                 1          NaN        NaN
4     2019.07.15 14:38:49                 1          NaN        NaN
...                   ...               ...          ...        ...
5666  2021.02.11 10:40:30                 1          NaN        NaN
5667  2021.02.11 10:40:30                 1          NaN        NaN
5668  2021.02.11 10:40:30                 1          NaN        NaN
5669  2021.02.11 10:40:30                 1          NaN        NaN
5670  2021.02.11 10:40:30                 1           No        NaN

      Saltwater Failsafe Iridium Command  Schedule Set Diagnostic Dive Data  \
0                    NaN             NaN     Roof Test                  NaN
1                    NaN             NaN     Roof Test                  NaN
2                    NaN             NaN     Roof Test                  NaN
3                    NaN             NaN     Roof Test                  NaN
4                    NaN             NaN     Roof Test                  NaN
...                  ...             ...           ...                  ...
5666                 NaN             NaN       Primary                  NaN
5667                 NaN             NaN       Primary                  NaN
5668                 NaN             NaN       Primary                  NaN
5669                 NaN             NaN       Primary                  NaN
5670                  No             NaN           NaN  0 0 13927 5 0 0 0 0

      Predeployment Data  Error
0                     No    NaN
1                     No    NaN
2                     No    NaN
3                     No    NaN
4                     No    NaN
...                  ...    ...
5666                  No    NaN
5667                  No    NaN
5668                  No    NaN
5669                  No    NaN
5670                  No    NaN

[5671 rows x 61 columns]

In [11]:
turtlesData[0].df

,Acquisition Time,Acquisition Start Time,Iridium CEP Radius,Iridium Latitude,Iridium Longitude,GPS Fix Time,GPS Fix Attempt,GPS Latitude,GPS Longitude,GPS UTM Zone,...,Receive Time,Repetition Count,Low Voltage,Mortality,Saltwater Failsafe,Iridium Command,Schedule Set,Diagnostic Dive Data,Predeployment Data,Error
0,2019.07.15 14:15:00,2019.07.15 14:15:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2019.07.15 14:40:24,1,NaN,NaN,NaN,NaN,Roof Test,NaN,No,NaN
1,2019.07.15 14:15:08,2019.07.15 14:15:00,NaN,NaN,NaN,2019.07.15 14:15:08,Resolved QFP,33.384364,-111.811310,12S,...,2019.07.15 14:40:24,1,NaN,NaN,NaN,NaN,Roof Test,NaN,No,NaN
2,2019.07.15 14:30:00,2019.07.15 14:15:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2019.07.15 14:40:24,1,NaN,NaN,NaN,NaN,Roof Test,NaN,No,NaN
3,2019.07.15 14:30:00,2019.07.15 14:30:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2019.07.15 14:40:24,1,NaN,NaN,NaN,NaN,Roof Test,NaN,No,NaN
4,2019.07.15 14:30:10,2019.07.15 14:30:00,NaN,NaN,NaN,2019.07.15 14:30:10,Resolved QFP,33.384385,-111.811292,12S,...,2019.07.15 14:40:24,1,NaN,NaN,NaN,NaN,Roof Test,NaN,No,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6903,2021.02.11 05:55:38,2021.02.11 05:00:00,NaN,NaN,NaN,2021.02.11 05:55:38,Resolved QFP,38.720644,11.825379,32S,...,2021.02.11 10:57:07,1,NaN,NaN,NaN,NaN,Primary,NaN,No,NaN
6904,2021.02.11 06:00:00,2021.02.11 04:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2021.02.11 10:57:07,1,NaN,NaN,NaN,NaN,Primary,NaN,No,NaN
6905,2021.02.11 06:00:10,2021.02.11 06:00:00,NaN,NaN,NaN,2021.02.11 06:00:10,Resolved QFP,38.720648,11.825217,32S,...,2021.02.11 10:57:07,1,NaN,NaN,NaN,NaN,Primary,NaN,No,NaN
6906,2021.02.11 08:00:00,2021.02.11 06:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2021.02.11 10:57:07,1,NaN,NaN,NaN,NaN,Primary,NaN,No,NaN
6907,2021.02.11 10:57:07,2021.02.11 10:57:07,3.0,38.72645,11.8152,NaN,NaN,NaN,NaN,NaN,...,2021.02.11 10:57:07,1,No,NaN,No,NaN,NaN,23094 7698 8878 3 0 0 2 1,No,NaN

In [12]:
turtlesData[1].df

,Acquisition Time,Acquisition Start Time,Iridium CEP Radius,Iridium Latitude,Iridium Longitude,GPS Fix Time,GPS Fix Attempt,GPS Latitude,GPS Longitude,GPS UTM Zone,...,Receive Time,Repetition Count,Low Voltage,Mortality,Saltwater Failsafe,Iridium Command,Schedule Set,Diagnostic Dive Data,Predeployment Data,Error
0,2019.07.15 14:15:00,2019.07.15 14:15:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2019.07.15 14:38:49,1,NaN,NaN,NaN,NaN,Roof Test,NaN,No,NaN
1,2019.07.15 14:15:08,2019.07.15 14:15:00,NaN,NaN,NaN,2019.07.15 14:15:08,Resolved QFP,33.384380,-111.811327,12S,...,2019.07.15 14:38:49,1,NaN,NaN,NaN,NaN,Roof Test,NaN,No,NaN
2,2019.07.15 14:30:00,2019.07.15 14:15:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2019.07.15 14:38:49,1,NaN,NaN,NaN,NaN,Roof Test,NaN,No,NaN
3,2019.07.15 14:30:00,2019.07.15 14:30:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2019.07.15 14:38:49,1,NaN,NaN,NaN,NaN,Roof Test,NaN,No,NaN
4,2019.07.15 14:30:06,2019.07.15 14:30:00,NaN,NaN,NaN,2019.07.15 14:30:06,Resolved QFP,33.384410,-111.811311,12S,...,2019.07.15 14:38:49,1,NaN,NaN,NaN,NaN,Roof Test,NaN,No,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5666,2021.02.11 04:00:00,2021.02.11 02:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2021.02.11 10:40:30,1,NaN,NaN,NaN,NaN,Primary,NaN,No,NaN
5667,2021.02.11 05:50:10,2021.02.11 05:00:00,NaN,NaN,NaN,2021.02.11 05:50:10,Resolved QFP,37.752154,17.380009,33S,...,2021.02.11 10:40:30,1,NaN,NaN,NaN,NaN,Primary,NaN,No,NaN
5668,2021.02.11 06:00:00,2021.02.11 04:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2021.02.11 10:40:30,1,NaN,NaN,NaN,NaN,Primary,NaN,No,NaN
5669,2021.02.11 06:41:28,2021.02.11 06:00:00,NaN,NaN,NaN,2021.02.11 06:41:28,Resolved QFP,37.742126,17.386460,33S,...,2021.02.11 10:40:30,1,NaN,NaN,NaN,NaN,Primary,NaN,No,NaN
5670,2021.02.11 10:40:30,2021.02.11 10:40:30,4.0,37.71965,17.37297,NaN,NaN,NaN,NaN,NaN,...,2021.02.11 10:40:30,1,No,NaN,No,NaN,NaN,0 0 13927 5 0 0 0 0,No,NaN

In [13]:
#turtlesData[0].df.loc[67:,:]

In [14]:
# sorting by Acquisition Time
turtlesData[0].df.sort_values("Acquisition Time", inplace = True)

In [15]:
turtlesData[0].df.loc[67:,:]

,Acquisition Time,Acquisition Start Time,Iridium CEP Radius,Iridium Latitude,Iridium Longitude,GPS Fix Time,GPS Fix Attempt,GPS Latitude,GPS Longitude,GPS UTM Zone,...,Receive Time,Repetition Count,Low Voltage,Mortality,Saltwater Failsafe,Iridium Command,Schedule Set,Diagnostic Dive Data,Predeployment Data,Error
67,2020.07.09 22:48:42,2020.07.09 22:48:42,2.0,37.92717,16.10175,NaN,NaN,NaN,NaN,NaN,...,2020.07.09 22:48:42,1,NaN,NaN,NaN,NaN,NaN,NaN,Yes,NaN
6908,2020.07.09 23:00:09,2020.07.09 23:00:00,NaN,NaN,NaN,2020.07.09 23:00:09,Resolved QFP (Uncertain),37.930044,16.068138,33S,...,2020.07.10 05:34:12,1,NaN,NaN,NaN,NaN,Primary,NaN,No,NaN
68,2020.07.09 23:00:09,2020.07.09 23:00:00,NaN,NaN,NaN,2020.07.09 23:00:09,Resolved QFP (Uncertain),37.930044,16.068138,33S,...,2020.07.10 05:34:12,1,NaN,NaN,NaN,NaN,Primary,NaN,No,NaN
69,2020.07.09 23:30:12,2020.07.09 23:30:00,NaN,NaN,NaN,2020.07.09 23:30:12,Resolved QFP,37.930187,16.068178,33S,...,2020.07.10 05:34:12,1,NaN,NaN,NaN,NaN,Primary,NaN,No,NaN
6909,2020.07.09 23:30:12,2020.07.09 23:30:00,NaN,NaN,NaN,2020.07.09 23:30:12,Resolved QFP,37.930187,16.068178,33S,...,2020.07.10 05:34:12,1,NaN,NaN,NaN,NaN,Primary,NaN,No,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6903,2021.02.11 05:55:38,2021.02.11 05:00:00,NaN,NaN,NaN,2021.02.11 05:55:38,Resolved QFP,38.720644,11.825379,32S,...,2021.02.11 10:57:07,1,NaN,NaN,NaN,NaN,Primary,NaN,No,NaN
6904,2021.02.11 06:00:00,2021.02.11 04:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2021.02.11 10:57:07,1,NaN,NaN,NaN,NaN,Primary,NaN,No,NaN
6905,2021.02.11 06:00:10,2021.02.11 06:00:00,NaN,NaN,NaN,2021.02.11 06:00:10,Resolved QFP,38.720648,11.825217,32S,...,2021.02.11 10:57:07,1,NaN,NaN,NaN,NaN,Primary,NaN,No,NaN
6906,2021.02.11 08:00:00,2021.02.11 06:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2021.02.11 10:57:07,1,NaN,NaN,NaN,NaN,Primary,NaN,No,NaN
6907,2021.02.11 10:57:07,2021.02.11 10:57:07,3.0,38.72645,11.81520,NaN,NaN,NaN,NaN,NaN,...,2021.02.11 10:57:07,1,No,NaN,No,NaN,NaN,23094 7698 8878 3 0 0 2 1,No,NaN

In [16]:
## dropping ALL duplicte values based on two columns
#turtlesData[0].df.drop_duplicates(
    #subset = ['Acquisition Time', 'Acquisition Start Time', 'Iridium CEP Radius'],
    #keep = 'last'
#).reset_index(drop = True)

In [17]:
## dropping ALL duplicte values based on two columns
#turtlesData[1].df.drop_duplicates(
    #subset = ['Acquisition Time', 'Acquisition Start Time', 'Iridium CEP Radius'],
    #keep = 'last'
#).reset_index(drop = True)

In [18]:
## dropping ALL duplicte values based on two columns
#turtlesData[0].df.drop_duplicates(
    #subset = ['Acquisition Start Time', 'Iridium CEP Radius', 'Layer 1 Percentage', 'GPS Latitude'],
    #keep = 'last'
#).reset_index(drop = True)

In [19]:
# dropping ALL duplicte values based on two columns
#turtlesData[1].df.drop_duplicates(
    #subset = ['Acquisition Start Time', 'Iridium CEP Radius', 'Layer 1 Percentage', 'GPS Latitude'],
    #keep = 'last'
#).reset_index(drop = True)

In [20]:
#turtlesData[0].df.loc[67:,:]

In [21]:
turtlesData[1].df

,Acquisition Time,Acquisition Start Time,Iridium CEP Radius,Iridium Latitude,Iridium Longitude,GPS Fix Time,GPS Fix Attempt,GPS Latitude,GPS Longitude,GPS UTM Zone,...,Receive Time,Repetition Count,Low Voltage,Mortality,Saltwater Failsafe,Iridium Command,Schedule Set,Diagnostic Dive Data,Predeployment Data,Error
0,2019.07.15 14:15:00,2019.07.15 14:15:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2019.07.15 14:38:49,1,NaN,NaN,NaN,NaN,Roof Test,NaN,No,NaN
1,2019.07.15 14:15:08,2019.07.15 14:15:00,NaN,NaN,NaN,2019.07.15 14:15:08,Resolved QFP,33.384380,-111.811327,12S,...,2019.07.15 14:38:49,1,NaN,NaN,NaN,NaN,Roof Test,NaN,No,NaN
2,2019.07.15 14:30:00,2019.07.15 14:15:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2019.07.15 14:38:49,1,NaN,NaN,NaN,NaN,Roof Test,NaN,No,NaN
3,2019.07.15 14:30:00,2019.07.15 14:30:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2019.07.15 14:38:49,1,NaN,NaN,NaN,NaN,Roof Test,NaN,No,NaN
4,2019.07.15 14:30:06,2019.07.15 14:30:00,NaN,NaN,NaN,2019.07.15 14:30:06,Resolved QFP,33.384410,-111.811311,12S,...,2019.07.15 14:38:49,1,NaN,NaN,NaN,NaN,Roof Test,NaN,No,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5666,2021.02.11 04:00:00,2021.02.11 02:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2021.02.11 10:40:30,1,NaN,NaN,NaN,NaN,Primary,NaN,No,NaN
5667,2021.02.11 05:50:10,2021.02.11 05:00:00,NaN,NaN,NaN,2021.02.11 05:50:10,Resolved QFP,37.752154,17.380009,33S,...,2021.02.11 10:40:30,1,NaN,NaN,NaN,NaN,Primary,NaN,No,NaN
5668,2021.02.11 06:00:00,2021.02.11 04:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2021.02.11 10:40:30,1,NaN,NaN,NaN,NaN,Primary,NaN,No,NaN
5669,2021.02.11 06:41:28,2021.02.11 06:00:00,NaN,NaN,NaN,2021.02.11 06:41:28,Resolved QFP,37.742126,17.386460,33S,...,2021.02.11 10:40:30,1,NaN,NaN,NaN,NaN,Primary,NaN,No,NaN
5670,2021.02.11 10:40:30,2021.02.11 10:40:30,4.0,37.71965,17.37297,NaN,NaN,NaN,NaN,NaN,...,2021.02.11 10:40:30,1,No,NaN,No,NaN,NaN,0 0 13927 5 0 0 0 0,No,NaN

In [22]:
# EXPLORING DATA
print(turtlesData[0].df.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9528 entries, 0 to 6907
Data columns (total 61 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Acquisition Time                  9528 non-null   object
 1   Acquisition Start Time            9528 non-null   object
 2   Iridium CEP Radius                730 non-null    float64
 3   Iridium Latitude                  730 non-null    float64
 4   Iridium Longitude                 730 non-null    float64
 5   GPS Fix Time                      4652 non-null   object
 6   GPS Fix Attempt                   4652 non-null   object
 7   GPS Latitude                      4652 non-null   float64
 8   GPS Longitude                     4652 non-null   float64
 9   GPS UTM Zone                      4652 non-null   object
 10  GPS UTM Northing                  4652 non-null   float64
 11  GPS UTM Easting                   4652 non-null   float64
 12  GPS Altitude                      4640 non-null   float64
 13  GPS Horizontal Error              12 non-null     float64
 14  GPS Horizontal Dilution           4640 non-null   float64
 15  GPS Satellite Bitmap              4640 non-null   object
 16  GPS Satellite Count               4640 non-null   float64
 17  Underwater Percentage             3480 non-null   object
 18  Dive Count                        3480 non-null   float64
 19  Average Dive Duration             3480 non-null   float64
 20  Dive Duration Standard Deviation  10 non-null     float64
 21  Maximum Dive Duration             10 non-null     float64
 22  Maximum Dive Depth                3480 non-null   float64
 23  Duration Limit 1 Dive Count       10 non-null     float64
 24  Duration Limit 2 Dive Count       10 non-null     float64
 25  Duration Limit 3 Dive Count       10 non-null     float64
 26  Duration Limit 4 Dive Count       10 non-null     float64
 27  Duration Limit 5 Dive Count       10 non-null     float64
 28  Duration Limit 6 Dive Count       10 non-null     float64
 29  Layer 1 Percentage                3480 non-null   object
 30  Layer 2 Percentage                3480 non-null   object
 31  Layer 3 Percentage                3480 non-null   object
 32  Layer 4 Percentage                3480 non-null   object
 33  Layer 5 Percentage                3480 non-null   object
 34  Layer 6 Percentage                3480 non-null   object
 35  Layer 7 Percentage                3470 non-null   object
 36  Layer 8 Percentage                3470 non-null   object
 37  Layer 9 Percentage                3470 non-null   object
 38  Layer 10 Percentage               3470 non-null   object
 39  Layer 1 Dive Count                3480 non-null   float64
 40  Layer 2 Dive Count                3480 non-null   float64
 41  Layer 3 Dive Count                3480 non-null   float64
 42  Layer 4 Dive Count                3480 non-null   float64
 43  Layer 5 Dive Count                3480 non-null   float64
 44  Layer 6 Dive Count                3480 non-null   float64
 45  Layer 7 Dive Count                3470 non-null   float64
 46  Layer 8 Dive Count                3470 non-null   float64
 47  Layer 9 Dive Count                3470 non-null   float64
 48  Layer 10 Dive Count               3470 non-null   float64
 49  Temperature                       598 non-null    float64
 50  Satellite Uplink                  798 non-null    object
 51  Receive Time                      9528 non-null   object
 52  Repetition Count                  9528 non-null   int64
 53  Low Voltage                       713 non-null    object
 54  Mortality                         0 non-null      float64
 55  Saltwater Failsafe                713 non-null    object
 56  Iridium Command                   2 non-null      object
 57  Schedule Set                      8720 non-null   object
 58  Diagnostic Dive Data              713 non-null    object
 59  Predeployment Data                9449 non-null   object
 60  Error                             52 non-null     object
dtypes: float64(34), int64(1), object(26)
memory usage: 4.8+ MB
None

In [23]:
# EXPLORING DATA
print(turtlesData[1].df.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5671 entries, 0 to 5670
Data columns (total 61 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Acquisition Time                  5671 non-null   object
 1   Acquisition Start Time            5671 non-null   object
 2   Iridium CEP Radius                458 non-null    float64
 3   Iridium Latitude                  458 non-null    float64
 4   Iridium Longitude                 458 non-null    float64
 5   GPS Fix Time                      2580 non-null   object
 6   GPS Fix Attempt                   2580 non-null   object
 7   GPS Latitude                      2580 non-null   float64
 8   GPS Longitude                     2580 non-null   float64
 9   GPS UTM Zone                      2580 non-null   object
 10  GPS UTM Northing                  2580 non-null   float64
 11  GPS UTM Easting                   2580 non-null   float64
 12  GPS Altitude                      2563 non-null   float64
 13  GPS Horizontal Error              17 non-null     float64
 14  GPS Horizontal Dilution           2563 non-null   float64
 15  GPS Satellite Bitmap              2563 non-null   object
 16  GPS Satellite Count               2563 non-null   float64
 17  Underwater Percentage             2197 non-null   object
 18  Dive Count                        2197 non-null   float64
 19  Average Dive Duration             2197 non-null   float64
 20  Dive Duration Standard Deviation  10 non-null     float64
 21  Maximum Dive Duration             10 non-null     float64
 22  Maximum Dive Depth                2197 non-null   float64
 23  Duration Limit 1 Dive Count       10 non-null     float64
 24  Duration Limit 2 Dive Count       10 non-null     float64
 25  Duration Limit 3 Dive Count       10 non-null     float64
 26  Duration Limit 4 Dive Count       10 non-null     float64
 27  Duration Limit 5 Dive Count       10 non-null     float64
 28  Duration Limit 6 Dive Count       10 non-null     float64
 29  Layer 1 Percentage                2197 non-null   object
 30  Layer 2 Percentage                2197 non-null   object
 31  Layer 3 Percentage                2197 non-null   object
 32  Layer 4 Percentage                2197 non-null   object
 33  Layer 5 Percentage                2197 non-null   object
 34  Layer 6 Percentage                2197 non-null   object
 35  Layer 7 Percentage                2187 non-null   object
 36  Layer 8 Percentage                2187 non-null   object
 37  Layer 9 Percentage                2187 non-null   object
 38  Layer 10 Percentage               2187 non-null   object
 39  Layer 1 Dive Count                2197 non-null   float64
 40  Layer 2 Dive Count                2197 non-null   float64
 41  Layer 3 Dive Count                2197 non-null   float64
 42  Layer 4 Dive Count                2197 non-null   float64
 43  Layer 5 Dive Count                2197 non-null   float64
 44  Layer 6 Dive Count                2197 non-null   float64
 45  Layer 7 Dive Count                2187 non-null   float64
 46  Layer 8 Dive Count                2187 non-null   float64
 47  Layer 9 Dive Count                2187 non-null   float64
 48  Layer 10 Dive Count               2187 non-null   float64
 49  Temperature                       387 non-null    float64
 50  Satellite Uplink                  504 non-null    object
 51  Receive Time                      5671 non-null   object
 52  Repetition Count                  5671 non-null   int64
 53  Low Voltage                       443 non-null    object
 54  Mortality                         0 non-null      float64
 55  Saltwater Failsafe                443 non-null    object
 56  Iridium Command                   8 non-null      object
 57  Schedule Set                      5146 non-null   object
 58  Diagnostic Dive Data              443 non-null    object
 59  Predeployment Data                5619 non-null   object
 60  Error                             24 non-null     object
dtypes: float64(34), int64(1), object(26)
memory usage: 2.7+ MB
None

In [24]:
print(turtlesData[0].df.describe())

       Iridium CEP Radius  Iridium Latitude  Iridium Longitude  GPS Latitude  \
count          730.000000        730.000000         730.000000   4652.000000
mean             8.212329         37.643475           8.206923     37.670528
std             37.757731          0.689978          11.945860      0.619987
min              2.000000         33.380400        -111.921280     31.440929
25%              3.000000         37.407615           5.145020     37.423018
50%              4.000000         37.873020           9.541380     37.884670
75%              6.000000         37.995750          12.732800     37.968790
max            681.000000         38.840670          16.200420     43.154531

       GPS Longitude  GPS UTM Northing  GPS UTM Easting  GPS Altitude  \
count    4652.000000      4.652000e+03      4652.000000   4640.000000
mean        9.138548      4.170645e+06    520107.400043      2.860776
std         7.708509      6.865701e+04    149940.953585    244.122964
min      -111.811369      3.479652e+06    234737.000000  -9573.000000
25%         5.489880      4.143682e+06    378902.750000      0.000000
50%         9.793805      4.193588e+06    574753.000000      7.000000
75%        14.441279      4.204008e+06    615671.250000     15.000000
max        16.123309      4.778737e+06    767488.000000   4051.000000

       GPS Horizontal Error  GPS Horizontal Dilution  ...  Layer 4 Dive Count  \
count             12.000000              4640.000000  ...         3480.000000
mean              19.456667                 3.545302  ...            0.226437
std                9.071262                 6.243582  ...            0.541353
min                9.090000                 0.700000  ...            0.000000
25%               10.500000                 1.100000  ...            0.000000
50%               18.370000                 1.400000  ...            0.000000
75%               29.500000                 2.200000  ...            0.000000
max               32.500000                25.500000  ...            4.000000

       Layer 5 Dive Count  Layer 6 Dive Count  Layer 7 Dive Count  \
count         3480.000000         3480.000000         3470.000000
mean             0.167241            0.117816            0.326513
std              0.468209            0.367435            0.726919
min              0.000000            0.000000            0.000000
25%              0.000000            0.000000            0.000000
50%              0.000000            0.000000            0.000000
75%              0.000000            0.000000            0.000000
max              4.000000            3.000000            4.000000

       Layer 8 Dive Count  Layer 9 Dive Count  Layer 10 Dive Count  \
count         3470.000000         3470.000000          3470.000000
mean             0.251009            0.062248             0.014986
std              0.644370            0.305873             0.126168
min              0.000000            0.000000             0.000000
25%              0.000000            0.000000             0.000000
50%              0.000000            0.000000             0.000000
75%              0.000000            0.000000             0.000000
max              4.000000            3.000000             2.000000

       Temperature  Repetition Count  Mortality
count   598.000000       9528.000000        0.0
mean     23.321070          1.008291        NaN
std       5.997816          0.090683        NaN
min      15.000000          1.000000        NaN
25%      19.000000          1.000000        NaN
50%      24.000000          1.000000        NaN
75%      27.000000          1.000000        NaN
max      56.000000          2.000000        NaN

[8 rows x 35 columns]

In [25]:
print(turtlesData[1].df.describe())

       Iridium CEP Radius  Iridium Latitude  Iridium Longitude  GPS Latitude  \
count          458.000000        458.000000         458.000000   2580.000000
mean             6.469432         38.246382          15.686954     38.315696
std             31.888141          1.060740          14.740181      0.945796
min              2.000000         33.353920        -111.905230     33.384328
25%              3.000000         37.637282          16.500727     37.689141
50%              4.000000         38.145135          17.447820     38.317028
75%              6.000000         39.107620          18.185008     39.058290
max            681.000000         40.191570          19.349470     47.202302

       GPS Longitude  GPS UTM Northing  GPS UTM Easting  GPS Altitude  \
count    2580.000000      2.580000e+03      2580.000000   2563.000000
mean       16.896963      4.243336e+06    529712.377132     10.245806
std         8.474671      1.059216e+05    196864.909400    229.620896
min      -111.811338      3.694189e+06    236829.000000  -4950.000000
25%        16.704789      4.172260e+06    280887.000000      1.000000
50%        17.739539      4.244228e+06    618082.000000      7.000000
75%        18.156575      4.326774e+06    685084.250000     13.500000
max        25.786379      5.228189e+06    763483.000000   7542.000000

       GPS Horizontal Error  GPS Horizontal Dilution  ...  Layer 4 Dive Count  \
count             17.000000              2563.000000  ...         2197.000000
mean              24.436471                 2.665704  ...            0.088757
std               23.459384                 4.842408  ...            0.301554
min                9.470000                 0.700000  ...            0.000000
25%               12.500000                 1.100000  ...            0.000000
50%               15.410000                 1.300000  ...            0.000000
75%               21.500000                 1.900000  ...            0.000000
max               98.500000                25.500000  ...            2.000000

       Layer 5 Dive Count  Layer 6 Dive Count  Layer 7 Dive Count  \
count         2197.000000          2197.00000         2187.000000
mean             0.101047             0.13564            0.171011
std              0.339806             0.42335            0.474434
min              0.000000             0.00000            0.000000
25%              0.000000             0.00000            0.000000
50%              0.000000             0.00000            0.000000
75%              0.000000             0.00000            0.000000
max              3.000000             3.00000            3.000000

       Layer 8 Dive Count  Layer 9 Dive Count  Layer 10 Dive Count  \
count         2187.000000         2187.000000          2187.000000
mean             0.106996            0.036123             0.003201
std              0.429346            0.242119             0.056497
min              0.000000            0.000000             0.000000
25%              0.000000            0.000000             0.000000
50%              0.000000            0.000000             0.000000
75%              0.000000            0.000000             0.000000
max              3.000000            3.000000             1.000000

       Temperature  Repetition Count  Mortality
count   387.000000       5671.000000        0.0
mean     22.552972          1.018515        NaN
std       6.649957          0.134817        NaN
min      15.000000          1.000000        NaN
25%      18.000000          1.000000        NaN
50%      21.000000          1.000000        NaN
75%      25.000000          1.000000        NaN
max      58.000000          2.000000        NaN

[8 rows x 35 columns]

In [26]:
# Filtering  the Starting Time Data and the Ending Time Data
startInfPeriod = turtlesData[0].df.iloc[0,1] # Element in the first row of dataframe and in the second column of the dataframe
endInfPeriod = turtlesData[0].df.iloc[-1,1]
print("System Information Data Collected between " + str(startInfPeriod) + " and " + str(endInfPeriod))

System Information Data Collected between 2019.07.15 14:15:00 and 2021.02.11 10:57:07

In [27]:
# Filtering  the Starting Time Data and the Ending Time Data
startInfPeriod = turtlesData[1].df.iloc[0,1] # Element in the first row of dataframe and in the second column of the dataframe
endInfPeriod = turtlesData[1].df.iloc[-1,1]
print("System Information Data Collected between " + str(startInfPeriod) + " and " + str(endInfPeriod))

System Information Data Collected between 2019.07.15 14:15:00 and 2021.02.11 10:40:30

In [31]:
def checkInstancesAndItsDfs(turtlesData):
    print('Created instances for Obj turtleData: ')
    for turtleData in turtlesData:        
        print(turtleData.getTag())
    print('--------------')
    print('Created Dataframes: ')
    i = 0
    for turtleData in turtlesData: 
        print(f'turtlesData[{i}].df')
        print(turtleData.df)
        print('--------------')
        i+=1

In [32]:
checkInstancesAndItsDfs(turtlesData)

Created instances for Obj turtleData:
710333a
710348a
--------------
Created Dataframes:
turtlesData[0].df
         Acquisition Time Acquisition Start Time  Iridium CEP Radius  \
0     2019.07.15 14:15:00    2019.07.15 14:15:00                 NaN
1     2019.07.15 14:15:08    2019.07.15 14:15:00                 NaN
2     2019.07.15 14:30:00    2019.07.15 14:15:00                 NaN
3     2019.07.15 14:30:00    2019.07.15 14:30:00                 NaN
4     2019.07.15 14:30:10    2019.07.15 14:30:00                 NaN
...                   ...                    ...                 ...
6903  2021.02.11 05:55:38    2021.02.11 05:00:00                 NaN
6904  2021.02.11 06:00:00    2021.02.11 04:00:00                 NaN
6905  2021.02.11 06:00:10    2021.02.11 06:00:00                 NaN
6906  2021.02.11 08:00:00    2021.02.11 06:00:00                 NaN
6907  2021.02.11 10:57:07    2021.02.11 10:57:07                 3.0

      Iridium Latitude  Iridium Longitude         GPS Fix Time  \
0                  NaN                NaN                  NaN
1                  NaN                NaN  2019.07.15 14:15:08
2                  NaN                NaN                  NaN
3                  NaN                NaN                  NaN
4                  NaN                NaN  2019.07.15 14:30:10
...                ...                ...                  ...
6903               NaN                NaN  2021.02.11 05:55:38
6904               NaN                NaN                  NaN
6905               NaN                NaN  2021.02.11 06:00:10
6906               NaN                NaN                  NaN
6907          38.72645            11.8152                  NaN

     GPS Fix Attempt  GPS Latitude  GPS Longitude GPS UTM Zone  ...  \
0                NaN           NaN            NaN          NaN  ...
1       Resolved QFP     33.384364    -111.811310          12S  ...
2                NaN           NaN            NaN          NaN  ...
3                NaN           NaN            NaN          NaN  ...
4       Resolved QFP     33.384385    -111.811292          12S  ...
...              ...           ...            ...          ...  ...
6903    Resolved QFP     38.720644      11.825379          32S  ...
6904             NaN           NaN            NaN          NaN  ...
6905    Resolved QFP     38.720648      11.825217          32S  ...
6906             NaN           NaN            NaN          NaN  ...
6907             NaN           NaN            NaN          NaN  ...

             Receive Time  Repetition Count  Low Voltage  Mortality  \
0     2019.07.15 14:40:24                 1          NaN        NaN
1     2019.07.15 14:40:24                 1          NaN        NaN
2     2019.07.15 14:40:24                 1          NaN        NaN
3     2019.07.15 14:40:24                 1          NaN        NaN
4     2019.07.15 14:40:24                 1          NaN        NaN
...                   ...               ...          ...        ...
6903  2021.02.11 10:57:07                 1          NaN        NaN
6904  2021.02.11 10:57:07                 1          NaN        NaN
6905  2021.02.11 10:57:07                 1          NaN        NaN
6906  2021.02.11 10:57:07                 1          NaN        NaN
6907  2021.02.11 10:57:07                 1           No        NaN

      Saltwater Failsafe Iridium Command  Schedule Set  \
0                    NaN             NaN     Roof Test
1                    NaN             NaN     Roof Test
2                    NaN             NaN     Roof Test
3                    NaN             NaN     Roof Test
4                    NaN             NaN     Roof Test
...                  ...             ...           ...
6903                 NaN             NaN       Primary
6904                 NaN             NaN       Primary
6905                 NaN             NaN       Primary
6906                 NaN             NaN       Primary
6907                  No             NaN           NaN

           Diagnostic Dive Data  Predeployment Data  Error
0                           NaN                  No    NaN
1                           NaN                  No    NaN
2                           NaN                  No    NaN
3                           NaN                  No    NaN
4                           NaN                  No    NaN
...                         ...                 ...    ...
6903                        NaN                  No    NaN
6904                        NaN                  No    NaN
6905                        NaN                  No    NaN
6906                        NaN                  No    NaN
6907  23094 7698 8878 3 0 0 2 1                  No    NaN

[9528 rows x 61 columns]
--------------
turtlesData[1].df
         Acquisition Time Acquisition Start Time  Iridium CEP Radius  \
0     2019.07.15 14:15:00    2019.07.15 14:15:00                 NaN
1     2019.07.15 14:15:08    2019.07.15 14:15:00                 NaN
2     2019.07.15 14:30:00    2019.07.15 14:15:00                 NaN
3     2019.07.15 14:30:00    2019.07.15 14:30:00                 NaN
4     2019.07.15 14:30:06    2019.07.15 14:30:00                 NaN
...                   ...                    ...                 ...
5666  2021.02.11 04:00:00    2021.02.11 02:00:00                 NaN
5667  2021.02.11 05:50:10    2021.02.11 05:00:00                 NaN
5668  2021.02.11 06:00:00    2021.02.11 04:00:00                 NaN
5669  2021.02.11 06:41:28    2021.02.11 06:00:00                 NaN
5670  2021.02.11 10:40:30    2021.02.11 10:40:30                 4.0

      Iridium Latitude  Iridium Longitude         GPS Fix Time  \
0                  NaN                NaN                  NaN
1                  NaN                NaN  2019.07.15 14:15:08
2                  NaN                NaN                  NaN
3                  NaN                NaN                  NaN
4                  NaN                NaN  2019.07.15 14:30:06
...                ...                ...                  ...
5666               NaN                NaN                  NaN
5667               NaN                NaN  2021.02.11 05:50:10
5668               NaN                NaN                  NaN
5669               NaN                NaN  2021.02.11 06:41:28
5670          37.71965           17.37297                  NaN

     GPS Fix Attempt  GPS Latitude  GPS Longitude GPS UTM Zone  ...  \
0                NaN           NaN            NaN          NaN  ...
1       Resolved QFP     33.384380    -111.811327          12S  ...
2                NaN           NaN            NaN          NaN  ...
3                NaN           NaN            NaN          NaN  ...
4       Resolved QFP     33.384410    -111.811311          12S  ...
...              ...           ...            ...          ...  ...
5666             NaN           NaN            NaN          NaN  ...
5667    Resolved QFP     37.752154      17.380009          33S  ...
5668             NaN           NaN            NaN          NaN  ...
5669    Resolved QFP     37.742126      17.386460          33S  ...
5670             NaN           NaN            NaN          NaN  ...

             Receive Time  Repetition Count  Low Voltage  Mortality  \
0     2019.07.15 14:38:49                 1          NaN        NaN
1     2019.07.15 14:38:49                 1          NaN        NaN
2     2019.07.15 14:38:49                 1          NaN        NaN
3     2019.07.15 14:38:49                 1          NaN        NaN
4     2019.07.15 14:38:49                 1          NaN        NaN
...                   ...               ...          ...        ...
5666  2021.02.11 10:40:30                 1          NaN        NaN
5667  2021.02.11 10:40:30                 1          NaN        NaN
5668  2021.02.11 10:40:30                 1          NaN        NaN
5669  2021.02.11 10:40:30                 1          NaN        NaN
5670  2021.02.11 10:40:30                 1           No        NaN

      Saltwater Failsafe Iridium Command  Schedule Set Diagnostic Dive Data  \
0                    NaN             NaN     Roof Test                  NaN
1                    NaN             NaN     Roof Test                  NaN
2                    NaN             NaN     Roof Test                  NaN
3                    NaN             NaN     Roof Test                  NaN
4                    NaN             NaN     Roof Test                  NaN
...                  ...             ...           ...                  ...
5666                 NaN             NaN       Primary                  NaN
5667                 NaN             NaN       Primary                  NaN
5668                 NaN             NaN       Primary                  NaN
5669                 NaN             NaN       Primary                  NaN
5670                  No             NaN           NaN  0 0 13927 5 0 0 0 0

      Predeployment Data  Error
0                     No    NaN
1                     No    NaN
2                     No    NaN
3                     No    NaN
4                     No    NaN
...                  ...    ...
5666                  No    NaN
5667                  No    NaN
5668                  No    NaN
5669                  No    NaN
5670                  No    NaN

[5671 rows x 61 columns]
--------------

In [29]:
# ------------------------ SAVE OVERRAL DF?
# ------------- EXAMPLE: #df.to_csv('Overall_Dataframe_Tag_333A_Data.csv', index=False)

In [30]:
# Clean Data, filtering 'no GPS Data' from 'GPS Data'