In [1]:
import pandas as pd
import os
import pyproj as pj # for reliable gps
import numpy as np # for reliable gps
from collections import Counter # for reliable gps
import datetime as dt # for reliable gps

In [18]:
# To run with terminal:
ASSETS_FOLDER = "assets"
ASSETS_FOLDER_ITENS = os.listdir(ASSETS_FOLDER)# ("assets")

DATACLEANINGRESULTS_FOLDER = "dataCleaningResults"
DATACLEANINGRESULTS_FOLDER_ITENS = os.listdir(DATACLEANINGRESULTS_FOLDER)# ("data_analysis/dataCleaningResults")

In [3]:
class TurtleData:
    """Commom base class for all turtle's data """
    
    C1 = 'Acquisition Time'
    C2 ='Acquisition Start Time'
    C3 ='Iridium CEP Radius'
    C4 ='Iridium Latitude'
    C5 ='Iridium Longitude'
    C6 ='GPS Fix Time'
    C7 ='GPS Fix Attempt'
    C8 ='GPS Latitude'
    C9 ='GPS Longitude'
    C10 ='GPS UTM Zone'
    C11 ='GPS UTM Northing'
    C12 ='GPS UTM Easting'
    C13 ='GPS Altitude'
    C14 ='GPS Horizontal Error'
    C15 ='GPS Horizontal Dilution'
    C16 ='GPS Satellite Bitmap'
    C17 ='GPS Satellite Count'
    C18 ='Underwater Percentage'
    C19 ='Dive Count'
    C20 ='Average Dive Duration'
    C21 ='Dive Duration Standard Deviation'
    C22 ='Maximum Dive Duration'
    C23 ='Maximum Dive Depth'
    C24 ='Duration Limit 1 Dive Count'
    C25 ='Duration Limit 2 Dive Count'
    C26 ='Duration Limit 3 Dive Count'
    C27 ='Duration Limit 4 Dive Count'
    C28 ='Duration Limit 5 Dive Count'
    C29 ='Duration Limit 6 Dive Count'
    C30 ='Layer 1 Percentage'
    C31 ='Layer 2 Percentage'
    C32 ='Layer 3 Percentage'
    C33 ='Layer 4 Percentage'
    C34 ='Layer 5 Percentage'
    C35 ='Layer 6 Percentage'
    C36 ='Layer 7 Percentage'
    C37 ='Layer 8 Percentage'
    C38 ='Layer 9 Percentage'
    C39 ='Layer 10 Percentage'
    C40 ='Layer 1 Dive Count'
    C41 ='Layer 2 Dive Count'
    C42 ='Layer 3 Dive Count'
    C43 ='Layer 4 Dive Count'
    C44 ='Layer 5 Dive Count'
    C45 ='Layer 6 Dive Count'
    C46 ='Layer 7 Dive Count'
    C47 ='Layer 8 Dive Count'
    C48 ='Layer 9 Dive Count'
    C49 ='Layer 10 Dive Count'
    C50 ='Temperature'
    C51 ='Satellite Uplink'
    C52 ='Receive Time'
    C53 ='Repetition Count'
    C54 ='Low Voltage'
    C55 ='Mortality'
    C56 ='Saltwater Failsafe'
    C57 ='Iridium Command'
    C58 ='Schedule Set'
    C59 ='Diagnostic Dive Data'
    C60 ='Predeployment Data'
    C61 ='Error'
    col_names = list([
        C1, C2, C3, C4, C5, C6, C7, C8, C9, C10, 
        C11, C12, C13, C14, C15, C16, C17, C18, C19, C20, 
        C21, C22, C23, C24, C25, C26, C27, C28, C29, C30, 
        C31, C32, C33, C34, C35, C36, C37, C38, C39, C40, 
        C41, C42, C43, C44, C45, C46, C47, C48, C49, C50, 
        C51, C52, C53, C54, C55, C56, C57, C58, C59, C60, 
        C61
    ])
    gps_col_names = list([
        C1, C2, C6, C7, C8, C9
    ])

    @staticmethod
    def calculateDistance(geodRef, lat1, lon1, lat2, lon2):
        v1,v2,dist = geodRef.inv(lat1,lon1,lat2,lon2) #Take the second row and the first row on the count. it shoul give 3 values, but I only need the dist.
        return dist #Put the dist inside the distances variable once empty.
    
    @staticmethod
    def convertUnixTimeFromString(timeString):
        return dt.datetime.strptime(timeString, '%Y.%m.%d %H:%M:%S').timestamp() #[i] is the position in an array
    
    @staticmethod
    def calculateSpeed(d, t1, t2):
        speed = d / (t2 - t1)
        return speed

    def __init__(self, tag):
        self.turtleTag = tag
        self.df = pd.DataFrame()
        self.allGpsDf = pd.DataFrame()
        self.reliableGpsDf = pd.DataFrame()
    #def addElement(self, row, header):
        #self.__dict__= dict(zip(header, row))

    def addDataFromCsv(self, filename):
        temporaryDf = pd.read_csv(filename, skiprows=23, names=TurtleData.col_names)
        
        #print(f' ITS CURRENT DF IS: {self.df}') 
        #print('--------------')
        #print(f' ITS TEMPORARY DF IS {temporaryDf}') 
        
        self.df = self.df.append(temporaryDf, ignore_index=True)
        self.df.sort_values("Acquisition Time", inplace = True)

    def getTag(self):
        return self.turtleTag

    def getDf(self):        
        return self.df
    
    def giveAllGpsDf(self):
        # see all the columns in the df
        #print(self.df.columns)
        # see one column at a time        
        self.allGpsDf = self.df.copy()
        print(TurtleData.gps_col_names)
        tempList = TurtleData.gps_col_names.copy()
        for c in self.allGpsDf.columns:
            print(c)            
            if c not in tempList:
                self.allGpsDf.drop(c, inplace=True, axis=1)
            else:
                tempList.remove(c)        

        if tempList:
            print("Colummn Data missing in!")
        else:
            print("The dataframe contains all the GPS columns")
        
        print('-----DF with NaN values ---------')
        print(self.allGpsDf)       
        
        #### Eliminate those GPS's null (NaN) rows from the dataframe
        self.allGpsDf.drop(self.allGpsDf[~self.allGpsDf['GPS Latitude'].notna()].index, inplace=True)
        self.allGpsDf.reset_index(drop=True, inplace=True) # reset index

        print('-----SAME DF without NaN values ---------')
        print(self.allGpsDf)

        ####Create a column for id GPS points to the left
        trackId = self.allGpsDf.index + 1
        self.allGpsDf.insert(0, 'Track ID', trackId)
        
        print(self.allGpsDf)        
        print(' End of all GPS Df ^')
        print('--------------')

In [4]:
TAG_TURTLE_1 = '710333A'
TAG_TURTLE_2 = '710348A'

INITIAL_TAG_DIGITS = '7103'

# Replace spaces in filenames with underlines
def replace_space_with_underline(file_name):
    return file_name.replace(" ", "_")

# Convert excel files into csv
def converting_excel_file_into_csv_file(folder_obj, file):        
    # read excel   
    df_xlsx = pd.read_excel(os.path.join(folder_obj, file))
    # change file format
    file_in_csv = file.replace(".xlsx", ".csv")
    # transform excel to csv file with path to store the CSV file
    df_xlsx.to_csv(os.path.join(folder_obj, file_in_csv), index = False)        

# Check if some excel file has not been converted into csv yet
def check_for_excel_files():
    all_my_files = []
    n = 0
    for file in ASSETS_FOLDER_ITENS:
        # put all the file names in the same format
        file = replace_space_with_underline(file).lower()
        all_my_files.append(file)
    
    # Create a copy of list
    for file in all_my_files[:]:
        if file.endswith('.xlsx'):
            print('- Excel file = ' + file)
            file_name = file.split('.', 1)[0] # remove everything (the format) after the dot
            # remove the excel file from my all_my_files list
            all_my_files.remove(file)            
            # check if another file with the same name in the folder exists
            if any(file_name in word for word in all_my_files):            
                print(f"-- Excellent! We've already converted the excel file \'{file_name}\' into csv file")
            else:
                print(f'-- Oh No! The excel file \'{file_name}\' has been not converted. Converting it into csv file...')
                # Call function "Convert excel files into csv"
                converting_excel_file_into_csv_file(ASSETS_FOLDER, file)
                file_in_csv = file.replace(".xlsx", ".csv") 
                all_my_files.append(file_in_csv)
                print('---> ' + file_in_csv + ' has been created!')
                
    # Updated all_my_files List
    print('--- CSV files in the assets folder: ', all_my_files)

def getTurtlesData():
    split_char = '_'
    csvs = []        
    turtlesData = []
    #turtleDfs = []
    for file in ASSETS_FOLDER_ITENS:
        if file.endswith('.csv'):
            # put all the file names in the same format
            csv_string_filename = replace_space_with_underline(file).lower()
            filename_splitted = csv_string_filename.split(split_char)                        
            for word in filename_splitted:
                if word.startswith(INITIAL_TAG_DIGITS):
                    csvs.append(file)
                    currentFileCsv = ASSETS_FOLDER + '\\' + file
                    print('--------------')
                    print("Found TAG ("+ word +") in filename , check if tag is already associated with an object...")

                    #--------------------
                                
                    foundTurtleData = None
                    # check inside the list if the turtle has already been created with that tag (word)
                    for obj in turtlesData:
                        if obj.getTag() == word:
                            foundTurtleData = obj
                            break    
                    #--------------------    
                                    
                    if foundTurtleData == None:
                        print("Instance for TAG ("+ word +") NOT found! Creating a new instance...")
                        # create a TurtleData obj with the turtle tag
                        foundTurtleData = TurtleData(word)
                        turtlesData.append(foundTurtleData)
                        print("Instance for TAG ("+ word +") CREATED!")
                    else:
                        print("Instance for TAG ("+ word +") ALREADY EXISTS, skipping object creation!")
                        print('--------------')

                    # for the instances turtleData objs in the list (for each turtle tag):
                    foundTurtleData.addDataFromCsv(currentFileCsv)                    

    return turtlesData

def checkInstancesAndItsDfs(turtlesData):
    print('Created instances for Obj turtleData: ')
    for turtleData in turtlesData:        
        print(turtleData.getTag())
    print('--------------')
    print('Created Dataframes: ')
    i = 0
    for turtleData in turtlesData: 
        print(f'turtlesData[{i}].df')
        print(turtleData.turtleTag)
        print(turtleData.df)
        print('--------------')
        i+=1

def getAllGpsDataframes(turtlesData):
    for turtleData in turtlesData:
        turtleData.giveAllGpsDf()

#def displayAllGpsDf(turtlesData):
    #for turtleData in turtlesData:
        #allGpsDf = turtleData.getAllGpsDf()
        #return allGpsDf.style.highlight_null(null_color='red')

In [5]:
# Check if some excel file has not been converted into csv yet
check_for_excel_files()
turtlesData = getTurtlesData()

# see instances for Obj turtleData created and its dataframes
checkInstancesAndItsDfs(turtlesData)   

# see dfs of all gps
getAllGpsDataframes(turtlesData)

- Excel file = mytest.xlsx
-- Excellent! We've already converted the excel file 'mytest' into csv file
- Excel file = tag_710333a_20_sept.xlsx
-- Excellent! We've already converted the excel file 'tag_710333a_20_sept' into csv file
--- CSV files in the assets folder:  ['710333a_93_condensed.csv', '710348a_49_condensed.csv', 'mytest.csv', 'tag_710333a_20_sept.csv']
--------------
Found TAG (710333a) in filename , check if tag is already associated with an object...
Instance for TAG (710333a) NOT found! Creating a new instance...
Instance for TAG (710333a) CREATED!
--------------
Found TAG (710348a) in filename , check if tag is already associated with an object...
Instance for TAG (710348a) NOT found! Creating a new instance...
Instance for TAG (710348a) CREATED!
--------------
Found TAG (710333a) in filename , check if tag is already associated with an object...
Instance for TAG (710333a) ALREADY EXISTS, skipping object creation!
--------------
Created instances for Obj turtleData:
710333a
710348a
--------------
Created Dataframes:
turtlesData[0].df
710333a
         Acquisition Time Acquisition Start Time  Iridium CEP Radius  \
0     2019.07.15 14:15:00    2019.07.15 14:15:00                 NaN
1     2019.07.15 14:15:08    2019.07.15 14:15:00                 NaN
2     2019.07.15 14:30:00    2019.07.15 14:15:00                 NaN
3     2019.07.15 14:30:00    2019.07.15 14:30:00                 NaN
4     2019.07.15 14:30:10    2019.07.15 14:30:00                 NaN
...                   ...                    ...                 ...
6903  2021.02.11 05:55:38    2021.02.11 05:00:00                 NaN
6904  2021.02.11 06:00:00    2021.02.11 04:00:00                 NaN
6905  2021.02.11 06:00:10    2021.02.11 06:00:00                 NaN
6906  2021.02.11 08:00:00    2021.02.11 06:00:00                 NaN
6907  2021.02.11 10:57:07    2021.02.11 10:57:07                 3.0

      Iridium Latitude  Iridium Longitude         GPS Fix Time  \
0                  NaN                NaN                  NaN
1                  NaN                NaN  2019.07.15 14:15:08
2                  NaN                NaN                  NaN
3                  NaN                NaN                  NaN
4                  NaN                NaN  2019.07.15 14:30:10
...                ...                ...                  ...
6903               NaN                NaN  2021.02.11 05:55:38
6904               NaN                NaN                  NaN
6905               NaN                NaN  2021.02.11 06:00:10
6906               NaN                NaN                  NaN
6907          38.72645            11.8152                  NaN

     GPS Fix Attempt  GPS Latitude  GPS Longitude GPS UTM Zone  ...  \
0                NaN           NaN            NaN          NaN  ...
1       Resolved QFP     33.384364    -111.811310          12S  ...
2                NaN           NaN            NaN          NaN  ...
3                NaN           NaN            NaN          NaN  ...
4       Resolved QFP     33.384385    -111.811292          12S  ...
...              ...           ...            ...          ...  ...
6903    Resolved QFP     38.720644      11.825379          32S  ...
6904             NaN           NaN            NaN          NaN  ...
6905    Resolved QFP     38.720648      11.825217          32S  ...
6906             NaN           NaN            NaN          NaN  ...
6907             NaN           NaN            NaN          NaN  ...

             Receive Time  Repetition Count  Low Voltage  Mortality  \
0     2019.07.15 14:40:24                 1          NaN        NaN
1     2019.07.15 14:40:24                 1          NaN        NaN
2     2019.07.15 14:40:24                 1          NaN        NaN
3     2019.07.15 14:40:24                 1          NaN        NaN
4     2019.07.15 14:40:24                 1          NaN        NaN
...                   ...               ...          ...        ...
6903  2021.02.11 10:57:07                 1          NaN        NaN
6904  2021.02.11 10:57:07                 1          NaN        NaN
6905  2021.02.11 10:57:07                 1          NaN        NaN
6906  2021.02.11 10:57:07                 1          NaN        NaN
6907  2021.02.11 10:57:07                 1           No        NaN

      Saltwater Failsafe Iridium Command  Schedule Set  \
0                    NaN             NaN     Roof Test
1                    NaN             NaN     Roof Test
2                    NaN             NaN     Roof Test
3                    NaN             NaN     Roof Test
4                    NaN             NaN     Roof Test
...                  ...             ...           ...
6903                 NaN             NaN       Primary
6904                 NaN             NaN       Primary
6905                 NaN             NaN       Primary
6906                 NaN             NaN       Primary
6907                  No             NaN           NaN

           Diagnostic Dive Data  Predeployment Data  Error
0                           NaN                  No    NaN
1                           NaN                  No    NaN
2                           NaN                  No    NaN
3                           NaN                  No    NaN
4                           NaN                  No    NaN
...                         ...                 ...    ...
6903                        NaN                  No    NaN
6904                        NaN                  No    NaN
6905                        NaN                  No    NaN
6906                        NaN                  No    NaN
6907  23094 7698 8878 3 0 0 2 1                  No    NaN

[9528 rows x 61 columns]
--------------
turtlesData[1].df
710348a
         Acquisition Time Acquisition Start Time  Iridium CEP Radius  \
0     2019.07.15 14:15:00    2019.07.15 14:15:00                 NaN
1     2019.07.15 14:15:08    2019.07.15 14:15:00                 NaN
2     2019.07.15 14:30:00    2019.07.15 14:15:00                 NaN
3     2019.07.15 14:30:00    2019.07.15 14:30:00                 NaN
4     2019.07.15 14:30:06    2019.07.15 14:30:00                 NaN
...                   ...                    ...                 ...
5666  2021.02.11 04:00:00    2021.02.11 02:00:00                 NaN
5667  2021.02.11 05:50:10    2021.02.11 05:00:00                 NaN
5668  2021.02.11 06:00:00    2021.02.11 04:00:00                 NaN
5669  2021.02.11 06:41:28    2021.02.11 06:00:00                 NaN
5670  2021.02.11 10:40:30    2021.02.11 10:40:30                 4.0

      Iridium Latitude  Iridium Longitude         GPS Fix Time  \
0                  NaN                NaN                  NaN
1                  NaN                NaN  2019.07.15 14:15:08
2                  NaN                NaN                  NaN
3                  NaN                NaN                  NaN
4                  NaN                NaN  2019.07.15 14:30:06
...                ...                ...                  ...
5666               NaN                NaN                  NaN
5667               NaN                NaN  2021.02.11 05:50:10
5668               NaN                NaN                  NaN
5669               NaN                NaN  2021.02.11 06:41:28
5670          37.71965           17.37297                  NaN

     GPS Fix Attempt  GPS Latitude  GPS Longitude GPS UTM Zone  ...  \
0                NaN           NaN            NaN          NaN  ...
1       Resolved QFP     33.384380    -111.811327          12S  ...
2                NaN           NaN            NaN          NaN  ...
3                NaN           NaN            NaN          NaN  ...
4       Resolved QFP     33.384410    -111.811311          12S  ...
...              ...           ...            ...          ...  ...
5666             NaN           NaN            NaN          NaN  ...
5667    Resolved QFP     37.752154      17.380009          33S  ...
5668             NaN           NaN            NaN          NaN  ...
5669    Resolved QFP     37.742126      17.386460          33S  ...
5670             NaN           NaN            NaN          NaN  ...

             Receive Time  Repetition Count  Low Voltage  Mortality  \
0     2019.07.15 14:38:49                 1          NaN        NaN
1     2019.07.15 14:38:49                 1          NaN        NaN
2     2019.07.15 14:38:49                 1          NaN        NaN
3     2019.07.15 14:38:49                 1          NaN        NaN
4     2019.07.15 14:38:49                 1          NaN        NaN
...                   ...               ...          ...        ...
5666  2021.02.11 10:40:30                 1          NaN        NaN
5667  2021.02.11 10:40:30                 1          NaN        NaN
5668  2021.02.11 10:40:30                 1          NaN        NaN
5669  2021.02.11 10:40:30                 1          NaN        NaN
5670  2021.02.11 10:40:30                 1           No        NaN

      Saltwater Failsafe Iridium Command  Schedule Set Diagnostic Dive Data  \
0                    NaN             NaN     Roof Test                  NaN
1                    NaN             NaN     Roof Test                  NaN
2                    NaN             NaN     Roof Test                  NaN
3                    NaN             NaN     Roof Test                  NaN
4                    NaN             NaN     Roof Test                  NaN
...                  ...             ...           ...                  ...
5666                 NaN             NaN       Primary                  NaN
5667                 NaN             NaN       Primary                  NaN
5668                 NaN             NaN       Primary                  NaN
5669                 NaN             NaN       Primary                  NaN
5670                  No             NaN           NaN  0 0 13927 5 0 0 0 0

      Predeployment Data  Error
0                     No    NaN
1                     No    NaN
2                     No    NaN
3                     No    NaN
4                     No    NaN
...                  ...    ...
5666                  No    NaN
5667                  No    NaN
5668                  No    NaN
5669                  No    NaN
5670                  No    NaN

[5671 rows x 61 columns]
--------------
['Acquisition Time', 'Acquisition Start Time', 'GPS Fix Time', 'GPS Fix Attempt', 'GPS Latitude', 'GPS Longitude']
Acquisition Time
Acquisition Start Time
Iridium CEP Radius
Iridium Latitude
Iridium Longitude
GPS Fix Time
GPS Fix Attempt
GPS Latitude
GPS Longitude
GPS UTM Zone
GPS UTM Northing
GPS UTM Easting
GPS Altitude
GPS Horizontal Error
GPS Horizontal Dilution
GPS Satellite Bitmap
GPS Satellite Count
Underwater Percentage
Dive Count
Average Dive Duration
Dive Duration Standard Deviation
Maximum Dive Duration
Maximum Dive Depth
Duration Limit 1 Dive Count

Duration Limit 2 Dive Count
Duration Limit 3 Dive Count
Duration Limit 4 Dive Count
Duration Limit 5 Dive Count
Duration Limit 6 Dive Count
Layer 1 Percentage
Layer 2 Percentage
Layer 3 Percentage
Layer 4 Percentage
Layer 5 Percentage
Layer 6 Percentage
Layer 7 Percentage
Layer 8 Percentage
Layer 9 Percentage
Layer 10 Percentage
Layer 1 Dive Count
Layer 2 Dive Count
Layer 3 Dive Count
Layer 4 Dive Count
Layer 5 Dive Count
Layer 6 Dive Count
Layer 7 Dive Count
Layer 8 Dive Count
Layer 9 Dive Count
Layer 10 Dive Count
Temperature
Satellite Uplink
Receive Time
Repetition Count
Low Voltage
Mortality
Saltwater Failsafe
Iridium Command
Schedule Set
Diagnostic Dive Data
Predeployment Data
Error
The dataframe contains all the GPS columns
-----DF with NaN values ---------
         Acquisition Time Acquisition Start Time         GPS Fix Time  \
0     2019.07.15 14:15:00    2019.07.15 14:15:00                  NaN
1     2019.07.15 14:15:08    2019.07.15 14:15:00  2019.07.15 14:15:08
2     2019.07.15 14:30:00    2019.07.15 14:15:00                  NaN
3     2019.07.15 14:30:00    2019.07.15 14:30:00                  NaN
4     2019.07.15 14:30:10    2019.07.15 14:30:00  2019.07.15 14:30:10
...                   ...                    ...                  ...
6903  2021.02.11 05:55:38    2021.02.11 05:00:00  2021.02.11 05:55:38
6904  2021.02.11 06:00:00    2021.02.11 04:00:00                  NaN
6905  2021.02.11 06:00:10    2021.02.11 06:00:00  2021.02.11 06:00:10
6906  2021.02.11 08:00:00    2021.02.11 06:00:00                  NaN
6907  2021.02.11 10:57:07    2021.02.11 10:57:07                  NaN

     GPS Fix Attempt  GPS Latitude  GPS Longitude
0                NaN           NaN            NaN
1       Resolved QFP     33.384364    -111.811310
2                NaN           NaN            NaN
3                NaN           NaN            NaN
4       Resolved QFP     33.384385    -111.811292
...              ...           ...            ...
6903    Resolved QFP     38.720644      11.825379
6904             NaN           NaN            NaN
6905    Resolved QFP     38.720648      11.825217
6906             NaN           NaN            NaN
6907             NaN           NaN            NaN

[9528 rows x 6 columns]
-----SAME DF without NaN values ---------
         Acquisition Time Acquisition Start Time         GPS Fix Time  \
0     2019.07.15 14:15:08    2019.07.15 14:15:00  2019.07.15 14:15:08
1     2019.07.15 14:30:10    2019.07.15 14:30:00  2019.07.15 14:30:10
2     2019.07.15 14:45:08    2019.07.15 14:45:00  2019.07.15 14:45:08
3     2019.07.15 15:00:10    2019.07.15 15:00:00  2019.07.15 15:00:10
4     2019.07.15 15:15:07    2019.07.15 15:15:00  2019.07.15 15:15:07
...                   ...                    ...                  ...
4647  2021.02.10 19:28:58    2021.02.10 19:00:00  2021.02.10 19:28:58
4648  2021.02.10 22:42:32    2021.02.10 22:00:00  2021.02.10 22:42:32
4649  2021.02.11 02:28:20    2021.02.11 02:00:00  2021.02.11 02:28:20
4650  2021.02.11 05:55:38    2021.02.11 05:00:00  2021.02.11 05:55:38
4651  2021.02.11 06:00:10    2021.02.11 06:00:00  2021.02.11 06:00:10

               GPS Fix Attempt  GPS Latitude  GPS Longitude
0                 Resolved QFP     33.384364    -111.811310
1                 Resolved QFP     33.384385    -111.811292
2                 Resolved QFP     33.384473    -111.811319
3                 Resolved QFP     33.384442    -111.811340
4     Resolved QFP (Uncertain)     33.384412    -111.811369
...                        ...           ...            ...
4647              Resolved QFP     38.754772      11.809630
4648              Resolved QFP     38.741873      11.821516
4649              Resolved QFP     38.727643      11.821051
4650              Resolved QFP     38.720644      11.825379
4651              Resolved QFP     38.720648      11.825217

[4652 rows x 6 columns]
      Track ID     Acquisition Time Acquisition Start Time  \
0            1  2019.07.15 14:15:08    2019.07.15 14:15:00
1            2  2019.07.15 14:30:10    2019.07.15 14:30:00
2            3  2019.07.15 14:45:08    2019.07.15 14:45:00
3            4  2019.07.15 15:00:10    2019.07.15 15:00:00
4            5  2019.07.15 15:15:07    2019.07.15 15:15:00
...        ...                  ...                    ...
4647      4648  2021.02.10 19:28:58    2021.02.10 19:00:00
4648      4649  2021.02.10 22:42:32    2021.02.10 22:00:00
4649      4650  2021.02.11 02:28:20    2021.02.11 02:00:00
4650      4651  2021.02.11 05:55:38    2021.02.11 05:00:00
4651      4652  2021.02.11 06:00:10    2021.02.11 06:00:00

             GPS Fix Time           GPS Fix Attempt  GPS Latitude  \
0     2019.07.15 14:15:08              Resolved QFP     33.384364
1     2019.07.15 14:30:10              Resolved QFP     33.384385
2     2019.07.15 14:45:08              Resolved QFP     33.384473
3     2019.07.15 15:00:10              Resolved QFP     33.384442
4     2019.07.15 15:15:07  Resolved QFP (Uncertain)     33.384412
...                   ...                       ...           ...
4647  2021.02.10 19:28:58              Resolved QFP     38.754772
4648  2021.02.10 22:42:32              Resolved QFP     38.741873
4649  2021.02.11 02:28:20              Resolved QFP     38.727643
4650  2021.02.11 05:55:38              Resolved QFP     38.720644
4651  2021.02.11 06:00:10              Resolved QFP     38.720648

      GPS Longitude
0       -111.811310
1       -111.811292
2       -111.811319
3       -111.811340
4       -111.811369
...             ...
4647      11.809630
4648      11.821516
4649      11.821051
4650      11.825379
4651      11.825217

[4652 rows x 7 columns]
 End of all GPS Df ^
--------------
['Acquisition Time', 'Acquisition Start Time', 'GPS Fix Time', 'GPS Fix Attempt', 'GPS Latitude', 'GPS Longitude']
Acquisition Time
Acquisition Start Time
Iridium CEP Radius
Iridium Latitude
Iridium Longitude
GPS Fix Time
GPS Fix Attempt
GPS Latitude
GPS Longitude
GPS UTM Zone
GPS UTM Northing
GPS UTM Easting
GPS Altitude
GPS Horizontal Error
GPS Horizontal Dilution
GPS Satellite Bitmap
GPS Satellite Count
Underwater Percentage
Dive Count
Average Dive Duration
Dive Duration Standard Deviation
Maximum Dive Duration
Maximum Dive Depth
Duration Limit 1 Dive Count
Duration Limit 2 Dive Count
Duration Limit 3 Dive Count
Duration Limit 4 Dive Count
Duration Limit 5 Dive Count
Duration Limit 6 Dive Count
Layer 1 Percentage
Layer 2 Percentage
Layer 3 Percentage
Layer 4 Percentage
Layer 5 Percentage
Layer 6 Percentage
Layer 7 Percentage
Layer 8 Percentage
Layer 9 Percentage
Layer 10 Percentage
Layer 1 Dive Count
Layer 2 Dive Count
Layer 3 Dive Count
Layer 4 Dive Count
Layer 5 Dive Count
Layer 6 Dive Count
Layer 7 Dive Count
Layer 8 Dive Count
Layer 9 Dive Count
Layer 10 Dive Count
Temperature
Satellite Uplink
Receive Time
Repetition Count
Low Voltage
Mortality
Saltwater Failsafe
Iridium Command
Schedule Set
Diagnostic Dive Data
Predeployment Data
Error
The dataframe contains all the GPS columns
-----DF with NaN values ---------
         Acquisition Time Acquisition Start Time         GPS Fix Time  \
0     2019.07.15 14:15:00    2019.07.15 14:15:00                  NaN
1     2019.07.15 14:15:08    2019.07.15 14:15:00  2019.07.15 14:15:08
2     2019.07.15 14:30:00    2019.07.15 14:15:00                  NaN
3     2019.07.15 14:30:00    2019.07.15 14:30:00                  NaN
4     2019.07.15 14:30:06    2019.07.15 14:30:00  2019.07.15 14:30:06
...                   ...                    ...                  ...
5666  2021.02.11 04:00:00    2021.02.11 02:00:00                  NaN
5667  2021.02.11 05:50:10    2021.02.11 05:00:00  2021.02.11 05:50:10
5668  2021.02.11 06:00:00    2021.02.11 04:00:00                  NaN
5669  2021.02.11 06:41:28    2021.02.11 06:00:00  2021.02.11 06:41:28
5670  2021.02.11 10:40:30    2021.02.11 10:40:30                  NaN

     GPS Fix Attempt  GPS Latitude  GPS Longitude
0                NaN           NaN            NaN
1       Resolved QFP     33.384380    -111.811327
2                NaN           NaN            NaN
3                NaN           NaN            NaN
4       Resolved QFP     33.384410    -111.811311
...              ...           ...            ...
5666             NaN           NaN            NaN
5667    Resolved QFP     37.752154      17.380009
5668             NaN           NaN            NaN
5669    Resolved QFP     37.742126      17.386460
5670             NaN           NaN            NaN

[5671 rows x 6 columns]
-----SAME DF without NaN values ---------
         Acquisition Time Acquisition Start Time         GPS Fix Time  \
0     2019.07.15 14:15:08    2019.07.15 14:15:00  2019.07.15 14:15:08
1     2019.07.15 14:30:06    2019.07.15 14:30:00  2019.07.15 14:30:06
2     2019.07.15 14:45:11    2019.07.15 14:45:00  2019.07.15 14:45:11
3     2019.07.15 15:00:07    2019.07.15 15:00:00  2019.07.15 15:00:07
4     2019.07.15 15:15:08    2019.07.15 15:15:00  2019.07.15 15:15:08
...                   ...                    ...                  ...
2575  2021.02.10 22:28:03    2021.02.10 22:00:00  2021.02.10 22:28:03
2576  2021.02.11 02:57:25    2021.02.11 02:00:00  2021.02.11 02:57:25
2577  2021.02.11 03:00:07    2021.02.11 03:00:00  2021.02.11 03:00:07
2578  2021.02.11 05:50:10    2021.02.11 05:00:00  2021.02.11 05:50:10
2579  2021.02.11 06:41:28    2021.02.11 06:00:00  2021.02.11 06:41:28

     GPS Fix Attempt  GPS Latitude  GPS Longitude
0       Resolved QFP     33.384380    -111.811327
1       Resolved QFP     33.384410    -111.811311
2       Resolved QFP     33.384463    -111.811327
3       Resolved QFP     33.384328    -111.811264
4       Resolved QFP     33.384443    -111.811241
...              ...           ...            ...
2575    Resolved QFP     37.799874      17.300539
2576    Resolved QFP     37.781820      17.352911
2577    Resolved QFP     37.781188      17.353534
2578    Resolved QFP     37.752154      17.380009
2579    Resolved QFP     37.742126      17.386460

[2580 rows x 6 columns]
      Track ID     Acquisition Time Acquisition Start Time  \
0            1  2019.07.15 14:15:08    2019.07.15 14:15:00
1            2  2019.07.15 14:30:06    2019.07.15 14:30:00
2            3  2019.07.15 14:45:11    2019.07.15 14:45:00
3            4  2019.07.15 15:00:07    2019.07.15 15:00:00
4            5  2019.07.15 15:15:08    2019.07.15 15:15:00
...        ...                  ...                    ...
2575      2576  2021.02.10 22:28:03    2021.02.10 22:00:00
2576      2577  2021.02.11 02:57:25    2021.02.11 02:00:00
2577      2578  2021.02.11 03:00:07    2021.02.11 03:00:00
2578      2579  2021.02.11 05:50:10    2021.02.11 05:00:00
2579      2580  2021.02.11 06:41:28    2021.02.11 06:00:00

             GPS Fix Time GPS Fix Attempt  GPS Latitude  GPS Longitude
0     2019.07.15 14:15:08    Resolved QFP     33.384380    -111.811327
1     2019.07.15 14:30:06    Resolved QFP     33.384410    -111.811311
2     2019.07.15 14:45:11    Resolved QFP     33.384463    -111.811327
3     2019.07.15 15:00:07    Resolved QFP     33.384328    -111.811264
4     2019.07.15 15:15:08    Resolved QFP     33.384443    -111.811241
...                   ...             ...           ...            ...
2575  2021.02.10 22:28:03    Resolved QFP     37.799874      17.300539
2576  2021.02.11 02:57:25    Resolved QFP     37.781820      17.352911
2577  2021.02.11 03:00:07    Resolved QFP     37.781188      17.353534
2578  2021.02.11 05:50:10    Resolved QFP     37.752154      17.380009
2579  2021.02.11 06:41:28    Resolved QFP     37.742126      17.386460

[2580 rows x 7 columns]
 End of all GPS Df ^
--------------

In [6]:
turtlesData[0].df

,Acquisition Time,Acquisition Start Time,Iridium CEP Radius,Iridium Latitude,Iridium Longitude,GPS Fix Time,GPS Fix Attempt,GPS Latitude,GPS Longitude,GPS UTM Zone,...,Receive Time,Repetition Count,Low Voltage,Mortality,Saltwater Failsafe,Iridium Command,Schedule Set,Diagnostic Dive Data,Predeployment Data,Error
0,2019.07.15 14:15:00,2019.07.15 14:15:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2019.07.15 14:40:24,1,NaN,NaN,NaN,NaN,Roof Test,NaN,No,NaN
1,2019.07.15 14:15:08,2019.07.15 14:15:00,NaN,NaN,NaN,2019.07.15 14:15:08,Resolved QFP,33.384364,-111.811310,12S,...,2019.07.15 14:40:24,1,NaN,NaN,NaN,NaN,Roof Test,NaN,No,NaN
2,2019.07.15 14:30:00,2019.07.15 14:15:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2019.07.15 14:40:24,1,NaN,NaN,NaN,NaN,Roof Test,NaN,No,NaN
3,2019.07.15 14:30:00,2019.07.15 14:30:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2019.07.15 14:40:24,1,NaN,NaN,NaN,NaN,Roof Test,NaN,No,NaN
4,2019.07.15 14:30:10,2019.07.15 14:30:00,NaN,NaN,NaN,2019.07.15 14:30:10,Resolved QFP,33.384385,-111.811292,12S,...,2019.07.15 14:40:24,1,NaN,NaN,NaN,NaN,Roof Test,NaN,No,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6903,2021.02.11 05:55:38,2021.02.11 05:00:00,NaN,NaN,NaN,2021.02.11 05:55:38,Resolved QFP,38.720644,11.825379,32S,...,2021.02.11 10:57:07,1,NaN,NaN,NaN,NaN,Primary,NaN,No,NaN
6904,2021.02.11 06:00:00,2021.02.11 04:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2021.02.11 10:57:07,1,NaN,NaN,NaN,NaN,Primary,NaN,No,NaN
6905,2021.02.11 06:00:10,2021.02.11 06:00:00,NaN,NaN,NaN,2021.02.11 06:00:10,Resolved QFP,38.720648,11.825217,32S,...,2021.02.11 10:57:07,1,NaN,NaN,NaN,NaN,Primary,NaN,No,NaN
6906,2021.02.11 08:00:00,2021.02.11 06:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2021.02.11 10:57:07,1,NaN,NaN,NaN,NaN,Primary,NaN,No,NaN
6907,2021.02.11 10:57:07,2021.02.11 10:57:07,3.0,38.72645,11.8152,NaN,NaN,NaN,NaN,NaN,...,2021.02.11 10:57:07,1,No,NaN,No,NaN,NaN,23094 7698 8878 3 0 0 2 1,No,NaN

In [7]:
turtlesData[1].df

,Acquisition Time,Acquisition Start Time,Iridium CEP Radius,Iridium Latitude,Iridium Longitude,GPS Fix Time,GPS Fix Attempt,GPS Latitude,GPS Longitude,GPS UTM Zone,...,Receive Time,Repetition Count,Low Voltage,Mortality,Saltwater Failsafe,Iridium Command,Schedule Set,Diagnostic Dive Data,Predeployment Data,Error
0,2019.07.15 14:15:00,2019.07.15 14:15:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2019.07.15 14:38:49,1,NaN,NaN,NaN,NaN,Roof Test,NaN,No,NaN
1,2019.07.15 14:15:08,2019.07.15 14:15:00,NaN,NaN,NaN,2019.07.15 14:15:08,Resolved QFP,33.384380,-111.811327,12S,...,2019.07.15 14:38:49,1,NaN,NaN,NaN,NaN,Roof Test,NaN,No,NaN
2,2019.07.15 14:30:00,2019.07.15 14:15:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2019.07.15 14:38:49,1,NaN,NaN,NaN,NaN,Roof Test,NaN,No,NaN
3,2019.07.15 14:30:00,2019.07.15 14:30:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2019.07.15 14:38:49,1,NaN,NaN,NaN,NaN,Roof Test,NaN,No,NaN
4,2019.07.15 14:30:06,2019.07.15 14:30:00,NaN,NaN,NaN,2019.07.15 14:30:06,Resolved QFP,33.384410,-111.811311,12S,...,2019.07.15 14:38:49,1,NaN,NaN,NaN,NaN,Roof Test,NaN,No,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5666,2021.02.11 04:00:00,2021.02.11 02:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2021.02.11 10:40:30,1,NaN,NaN,NaN,NaN,Primary,NaN,No,NaN
5667,2021.02.11 05:50:10,2021.02.11 05:00:00,NaN,NaN,NaN,2021.02.11 05:50:10,Resolved QFP,37.752154,17.380009,33S,...,2021.02.11 10:40:30,1,NaN,NaN,NaN,NaN,Primary,NaN,No,NaN
5668,2021.02.11 06:00:00,2021.02.11 04:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2021.02.11 10:40:30,1,NaN,NaN,NaN,NaN,Primary,NaN,No,NaN
5669,2021.02.11 06:41:28,2021.02.11 06:00:00,NaN,NaN,NaN,2021.02.11 06:41:28,Resolved QFP,37.742126,17.386460,33S,...,2021.02.11 10:40:30,1,NaN,NaN,NaN,NaN,Primary,NaN,No,NaN
5670,2021.02.11 10:40:30,2021.02.11 10:40:30,4.0,37.71965,17.37297,NaN,NaN,NaN,NaN,NaN,...,2021.02.11 10:40:30,1,No,NaN,No,NaN,NaN,0 0 13927 5 0 0 0 0,No,NaN

In [8]:
turtlesData[0].allGpsDf

,Track ID,Acquisition Time,Acquisition Start Time,GPS Fix Time,GPS Fix Attempt,GPS Latitude,GPS Longitude
0,1,2019.07.15 14:15:08,2019.07.15 14:15:00,2019.07.15 14:15:08,Resolved QFP,33.384364,-111.811310
1,2,2019.07.15 14:30:10,2019.07.15 14:30:00,2019.07.15 14:30:10,Resolved QFP,33.384385,-111.811292
2,3,2019.07.15 14:45:08,2019.07.15 14:45:00,2019.07.15 14:45:08,Resolved QFP,33.384473,-111.811319
3,4,2019.07.15 15:00:10,2019.07.15 15:00:00,2019.07.15 15:00:10,Resolved QFP,33.384442,-111.811340
4,5,2019.07.15 15:15:07,2019.07.15 15:15:00,2019.07.15 15:15:07,Resolved QFP (Uncertain),33.384412,-111.811369
...,...,...,...,...,...,...,...
4647,4648,2021.02.10 19:28:58,2021.02.10 19:00:00,2021.02.10 19:28:58,Resolved QFP,38.754772,11.809630
4648,4649,2021.02.10 22:42:32,2021.02.10 22:00:00,2021.02.10 22:42:32,Resolved QFP,38.741873,11.821516
4649,4650,2021.02.11 02:28:20,2021.02.11 02:00:00,2021.02.11 02:28:20,Resolved QFP,38.727643,11.821051
4650,4651,2021.02.11 05:55:38,2021.02.11 05:00:00,2021.02.11 05:55:38,Resolved QFP,38.720644,11.825379
4651,4652,2021.02.11 06:00:10,2021.02.11 06:00:00,2021.02.11 06:00:10,Resolved QFP,38.720648,11.825217

In [9]:
turtlesData[1].allGpsDf

,Track ID,Acquisition Time,Acquisition Start Time,GPS Fix Time,GPS Fix Attempt,GPS Latitude,GPS Longitude
0,1,2019.07.15 14:15:08,2019.07.15 14:15:00,2019.07.15 14:15:08,Resolved QFP,33.384380,-111.811327
1,2,2019.07.15 14:30:06,2019.07.15 14:30:00,2019.07.15 14:30:06,Resolved QFP,33.384410,-111.811311
2,3,2019.07.15 14:45:11,2019.07.15 14:45:00,2019.07.15 14:45:11,Resolved QFP,33.384463,-111.811327
3,4,2019.07.15 15:00:07,2019.07.15 15:00:00,2019.07.15 15:00:07,Resolved QFP,33.384328,-111.811264
4,5,2019.07.15 15:15:08,2019.07.15 15:15:00,2019.07.15 15:15:08,Resolved QFP,33.384443,-111.811241
...,...,...,...,...,...,...,...
2575,2576,2021.02.10 22:28:03,2021.02.10 22:00:00,2021.02.10 22:28:03,Resolved QFP,37.799874,17.300539
2576,2577,2021.02.11 02:57:25,2021.02.11 02:00:00,2021.02.11 02:57:25,Resolved QFP,37.781820,17.352911
2577,2578,2021.02.11 03:00:07,2021.02.11 03:00:00,2021.02.11 03:00:07,Resolved QFP,37.781188,17.353534
2578,2579,2021.02.11 05:50:10,2021.02.11 05:00:00,2021.02.11 05:50:10,Resolved QFP,37.752154,17.380009
2579,2580,2021.02.11 06:41:28,2021.02.11 06:00:00,2021.02.11 06:41:28,Resolved QFP,37.742126,17.386460

In [16]:
def displayAllGpsDf(turtlesData):
    i = 0
    for turtleData in turtlesData:
        print(f'turtlesData[{i}].allGpsDf')
        print(turtleData.turtleTag)
        print(turtleData.allGpsDf)

In [17]:
displayAllGpsDf(turtlesData)

turtlesData[0].allGpsDf
710333a
      Track ID     Acquisition Time Acquisition Start Time  \
0            1  2019.07.15 14:15:08    2019.07.15 14:15:00
1            2  2019.07.15 14:30:10    2019.07.15 14:30:00
2            3  2019.07.15 14:45:08    2019.07.15 14:45:00
3            4  2019.07.15 15:00:10    2019.07.15 15:00:00
4            5  2019.07.15 15:15:07    2019.07.15 15:15:00
...        ...                  ...                    ...
4647      4648  2021.02.10 19:28:58    2021.02.10 19:00:00
4648      4649  2021.02.10 22:42:32    2021.02.10 22:00:00
4649      4650  2021.02.11 02:28:20    2021.02.11 02:00:00
4650      4651  2021.02.11 05:55:38    2021.02.11 05:00:00
4651      4652  2021.02.11 06:00:10    2021.02.11 06:00:00

             GPS Fix Time           GPS Fix Attempt  GPS Latitude  \
0     2019.07.15 14:15:08              Resolved QFP     33.384364
1     2019.07.15 14:30:10              Resolved QFP     33.384385
2     2019.07.15 14:45:08              Resolved QFP     33.384473
3     2019.07.15 15:00:10              Resolved QFP     33.384442
4     2019.07.15 15:15:07  Resolved QFP (Uncertain)     33.384412
...                   ...                       ...           ...
4647  2021.02.10 19:28:58              Resolved QFP     38.754772
4648  2021.02.10 22:42:32              Resolved QFP     38.741873
4649  2021.02.11 02:28:20              Resolved QFP     38.727643
4650  2021.02.11 05:55:38              Resolved QFP     38.720644
4651  2021.02.11 06:00:10              Resolved QFP     38.720648

      GPS Longitude
0       -111.811310
1       -111.811292
2       -111.811319
3       -111.811340
4       -111.811369
...             ...
4647      11.809630
4648      11.821516
4649      11.821051
4650      11.825379
4651      11.825217

[4652 rows x 7 columns]
turtlesData[0].allGpsDf
710348a
      Track ID     Acquisition Time Acquisition Start Time  \
0            1  2019.07.15 14:15:08    2019.07.15 14:15:00
1            2  2019.07.15 14:30:06    2019.07.15 14:30:00
2            3  2019.07.15 14:45:11    2019.07.15 14:45:00
3            4  2019.07.15 15:00:07    2019.07.15 15:00:00
4            5  2019.07.15 15:15:08    2019.07.15 15:15:00
...        ...                  ...                    ...
2575      2576  2021.02.10 22:28:03    2021.02.10 22:00:00
2576      2577  2021.02.11 02:57:25    2021.02.11 02:00:00
2577      2578  2021.02.11 03:00:07    2021.02.11 03:00:00
2578      2579  2021.02.11 05:50:10    2021.02.11 05:00:00
2579      2580  2021.02.11 06:41:28    2021.02.11 06:00:00

             GPS Fix Time GPS Fix Attempt  GPS Latitude  GPS Longitude
0     2019.07.15 14:15:08    Resolved QFP     33.384380    -111.811327
1     2019.07.15 14:30:06    Resolved QFP     33.384410    -111.811311
2     2019.07.15 14:45:11    Resolved QFP     33.384463    -111.811327
3     2019.07.15 15:00:07    Resolved QFP     33.384328    -111.811264
4     2019.07.15 15:15:08    Resolved QFP     33.384443    -111.811241
...                   ...             ...           ...            ...
2575  2021.02.10 22:28:03    Resolved QFP     37.799874      17.300539
2576  2021.02.11 02:57:25    Resolved QFP     37.781820      17.352911
2577  2021.02.11 03:00:07    Resolved QFP     37.781188      17.353534
2578  2021.02.11 05:50:10    Resolved QFP     37.752154      17.380009
2579  2021.02.11 06:41:28    Resolved QFP     37.742126      17.386460

[2580 rows x 7 columns]

In [27]:
def displayAllGpsDf(turtlesData):
    i = 0
    for turtleData in turtlesData:
        print(f'turtlesData[{i}].allGpsDf')
        print(turtleData.turtleTag)
        #print(turtleData.allGpsDf)
        #print(pd.concat([turtleData.allGpsDf['Acquisition Time'].head(1), turtleData.allGpsDf['Acquisition Time'].tail(1)]))
        print(turtleData.allGpsDf['Acquisition Time'].tail(1))

In [28]:
displayAllGpsDf(turtlesData)

turtlesData[0].allGpsDf
710333a
4651    2021.02.11 06:00:10
Name: Acquisition Time, dtype: object
turtlesData[0].allGpsDf
710348a
2579    2021.02.11 06:41:28
Name: Acquisition Time, dtype: object

In [115]:
def checkIfAllGpsDfHasBeenSaved(turtlesData):
    # create a name for each turtleData
    i = 0
    for turtleData in turtlesData:
        #print(f'turtlesData[{i}].allGpsDf')
        #print(turtleData.turtleTag)
        #print(turtleData.allGpsDf)
        #print(pd.concat([turtleData.allGpsDf['Acquisition Time'].head(1), turtleData.allGpsDf['Acquisition Time'].tail(1)]))
        # Last entry:
        lastEntry = turtleData.allGpsDf['Acquisition Time'].tail(1)
        #print(lastEntry)
        lastEntry = pd.Series([[y for y in x.split()] for x in lastEntry])
        #print(lastEntry)
        for value in enumerate(lastEntry):
            #print(value[1][0])
            lastDate = value[1][0]
            date = dt.datetime.strptime(lastDate, "%Y.%m.%d")
            stringDate = date.strftime("%Y") + "_" + date.strftime("%b")
            print(f"The Last Entry in the Dataframe for {turtleData.turtleTag} is from: ")
            print(stringDate)
            # Give the CSV a Name based on this values above
            # name = allGpsDf_tag_xxxxx_until_lastdate
            cvsName = "allGpsDf" + "_Tag_" + turtleData.turtleTag + "_" + stringDate +".csv"
            print(f"The Name of the CSV for the turtlesData[{i}].allGpsDf data is: ")
            print(cvsName)
            print('--------------')
        i+=1

In [116]:
checkIfAllGpsDfHasBeenSaved(turtlesData)

The Last Entry in the Dataframe for 710333a is from:
2021_Feb
The Name of the CSV for the turtlesData[0].allGpsDf data is:
allGpsDf_Tag_710333a_2021_Feb.csv
--------------
The Last Entry in the Dataframe for 710348a is from:
2021_Feb
The Name of the CSV for the turtlesData[1].allGpsDf data is:
allGpsDf_Tag_710348a_2021_Feb.csv
--------------

#### if this file already exists in the folder do not save it. See scripts_rewrite_proj1_jupyter_5